### ISSUE TITLE
meta dll file missing..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#1]
where is meta plugins ?

**Comment by SmileYzn** [comment]
Download manually, it is metamod-r.

Em dom., 5 de mar. de 2023 13:58, Muhammad Humza Shafique <
***@***.***> escreveu:

**Comment by Escap3d** [comment]
I dont have a compiler do u have compile software can u share me how to compile file..

**Comment by SmileYzn** [comment]
Did you look at actions builds? There is dlls of mod

**Comment by SmileYzn** [comment]
I will close this issue as solved, since i have made only actions builds.
