### ISSUE TITLE
second half issue 

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#10]
Second half start start money 800 and not increase money and !restart cmd not working some time plz fix it

**Comment by SmileYzn** [comment]
Describe a lot better what happen about money. What is wrong?
You should learn how mp_startmoney works and where change it if is the case.

About !restart, there can be restarted only at first half. See what message is returning in chat or even if you added admin rights to users.ini.

Please elaborate questions, not only ask for fixes.

**Comment by Escap3d** [comment]
By the way ur matchbot mod i like it thanks
