### ISSUE TITLE
<matchbot_mm.so>  badf load  matchbot_mm.so

### ISSUE THREAD

**Issue by that-is-not-great** [SmileYzn/MatchBot#100]
sorry me again. I setup a new clean server, and tried the latest builds from you
https://github.com/SmileYzn/MatchBot/actions/runs/6040384960
https://github.com/SmileYzn/MatchBot/actions/runs/6001682898

both get error `badf load`

ubuntu 20.04

```
meta list
Currently loaded plugins:
      description       stat pend  file                    vers      src  load  unload
 [ 1] SafeNameAndChat   RUN   -    SafeNameAndChat_1.1.so  v1.1      ini  ANY   ANY  
 [ 2] Reunion           RUN   -    reunion_mm_i386.so      v0.1.92d  ini  Start Never
 [ 3] ReAuthCheck       RUN   -    reauthcheck_mm_i386.so  v0.1.6    ini  Start Never
 [ 4] <matchbot_mm.so>  badf load  matchbot_mm.so          v -       ini   -     -   
 [ 5] HitBox Fix        RUN   -    hitbox_fix_mm_i386.so   v1.1.4    ini  Start ANY  
 [ 6] Accuracy Fix      RUN   -    accuracyfix_mm.so       v1.0.2    ini  ANY   ANY  
6 plugins, 5 running
version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.13.0.788-dev
Build date: 07:36:33 Jul 12 2023 (3378)
Build from: https://github.com/dreamstalker/rehlds/commit/f955b07
game version
ReGameDLL version: 5.22.0.593-dev
Build date: 03:10:30 Jul 11 2023
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/e1d1c11
meta version
Metamod-r v1.3.0.131, API (5:13)
Metamod-r build: 18:51:02 Jul 11 2022
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/adc9414
```

how can I debug this further? I put log on, `debuglevel 9`, what else?

the only version that worked on this same server now was the release `v1.0.0`

```
Currently loaded plugins:
      description      stat pend  file                    vers      src  load  unload
 [ 1] SafeNameAndChat  RUN   -    SafeNameAndChat_1.1.so  v1.1      ini  ANY   ANY  
 [ 2] Reunion          RUN   -    reunion_mm_i386.so      v0.1.92d  ini  Start Never
 [ 3] ReAuthCheck      RUN   -    reauthcheck_mm_i386.so  v0.1.6    ini  Start Never
 [ 4] Match Bot        RUN   -    matchbot_mm.so          v1.0.0    ini  ANY   ANY  
 [ 5] HitBox Fix       RUN   -    hitbox_fix_mm_i386.so   v1.1.4    ini  Start ANY  
 [ 6] Accuracy Fix     RUN   -    accuracyfix_mm.so       v1.0.2    ini  ANY   ANY  
6 plugins, 6 running
```

**Comment by axl303** [comment]
Try with debuglevel 42 (metamod) and +log on in startup console parameters (when starting server) and see what it gives.

**Comment by axl303** [comment]
I had a similar issue on one of smiley's projects before and he solved it by making: Temporary fixed with -static-libstdc++ in Makefile

Tho you may want to try the static linked one from actions if you have time (linux build) https://github.com/SmileYzn/MatchBot/actions/runs/5911367305 just for a test. 

@SmileYzn will tell more when he is on pc.

**Comment by SmileYzn** [comment]
VALVe static linked these shits to their own HLDS server.

Try it this action build:
https://github.com/SmileYzn/MatchBot/actions/runs/6163496524

I hope that works

**Comment by SmileYzn** [comment]
> thx a lot yes this one works, so the diff is this added?
> 
> `-static-libgcc -static-libstdc++` ?
> 
> ```
> meta list
> Currently loaded plugins:
>       description      stat pend  file                    vers      src  load  unload
>  [ 1] SafeNameAndChat  RUN   -    SafeNameAndChat_1.1.so  v1.1      ini  ANY   ANY  
>  [ 2] Reunion          RUN   -    reunion_mm_i386.so      v0.1.92d  ini  Start Never
>  [ 3] ReAuthCheck      RUN   -    reauthcheck_mm_i386.so  v0.1.6    ini  Start Never
>  [ 4] Match Bot        RUN   -    matchbot_mm.so          v1.0.0    ini  ANY   ANY  
>  [ 5] HitBox Fix       RUN   -    hitbox_fix_mm_i386.so   v1.1.4    ini  Start ANY  
>  [ 6] Accuracy Fix     RUN   -    accuracyfix_mm.so       v1.0.2    ini  ANY   ANY  
> 6 plugins, 6 running
> ```

Yes, static linked
