### ISSUE TITLE
[Bug] Player List User Issue

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#101]
Hi, I was looking on player list menu tests and got a bug. 

When player do retry he gets reconect and new userid. 

The old one put that player was offline. 

But if you change screen resolution or something that restart your game. 

When player gets reconected after doing his game changes the old one appers on last team he was playing. 

And it gets you hability to kick ban slay, but since userindex was is for old player it gets like player X not connected. 

Hope video explain better.

https://www.youtube.com/watch?v=JT5pwUeMWjY

**Comment by SmileYzn** [comment]
Try to fix player list using steam id instead of user id

Linux: https://github.com/SmileYzn/MatchBot/actions/runs/7626752289
Windows: https://github.com/SmileYzn/MatchBot/actions/runs/7626752288
