### ISSUE TITLE
[BUG] Wrong time wait when player did retry or disconnect

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#102]
Hi, I put today for test mb_retry_mode 1 and mb_retry_time "60"

Some players got something like this. 

![image](https://github.com/SmileYzn/MatchBot/assets/74840575/04d8aa7c-80c8-4bf9-b2b8-4162edcce3cd)

was 6000 seconds, 

10k seconds. 

I was testing and could not get it simulated. But players had this issue. I disabled retry time.

**Comment by SmileYzn** [comment]
Did server has online for very long time?
This can be a bug with gpGlobals->time

**Comment by SmileYzn** [comment]
@yuyiken 

Try to fix with sv_rehlds_local_gametime 1

**Comment by SmileYzn** [comment]
@yuyiken 

Notices about it? I will close issue
