### ISSUE TITLE
Win Rehlds commands error ..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#105]
![Screenshot 2023-12-08 215604](https://github.com/SmileYzn/MatchBot/assets/78939962/172146d1-d775-4363-b89d-f216de06c70b)

**Comment by Escap3d** [comment]
Plzz fix on it…

**Comment by NapsteRRRRRRRRRRRRR** [comment]
No command works from .ready to admin command..

**Comment by SmileYzn** [comment]
It is duplicated of #103

**Comment by Escap3d** [comment]
> ![Screenshot 2023-12-08 215604](https://private-user-images.githubusercontent.com/78939962/289137775-172146d1-d775-4363-b89d-f216de06c70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDc0OTAsIm5iZiI6MTcwMjkwNzE5MCwicGF0aCI6Ii83ODkzOTk2Mi8yODkxMzc3NzUtMTcyMTQ2ZDEtZDc3NS00MzYzLWI4OWQtZjIxNmRlMDZjNzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEzNDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YTE4Y2M1YTZjYjA5YTNkYjAxOWY1MzhjZWEwZmQ2Y2VjMDVkZjBmM2E3MDY4NDM1ZGM0YzRkZDNiYzE1YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L0oXXbo-H-93yPgVa6NH5wAFY8WyDirup-Urr7cGCaY)

how can i fix it ???
