### ISSUE TITLE
I would suggest integrating match statistics into the module and utilizing the data from matchstats. This would enhance the overall experience of the matches and ensure fairness.

### ISSUE THREAD

**Issue by tarimren-admin** [SmileYzn/MatchBot#108]
1、Integrate matchstats into the matchbot module, so that it can exist as a complete match module.
2、Add player 1vN (1V3, 1V4, 1V5) data to matchstats to increase the game's appeal.
3、Referencing the CS.GO or fastcup mode, add player skill rating information to matchstats to ensure balanced matchmaking between two teams.

**Comment by SmileYzn** [comment]
Ok, start pull requests i will review and merge it 😆
