### ISSUE TITLE
Suggestion for votemap cutting.

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#11]
Can u add for votemap cutting in this mod just like fastcup before match votemap cutting for last final map..

**Comment by SmileYzn** [comment]
Did you can try to explain better?
I have added a votemap automatically at match end.

**Comment by SmileYzn** [comment]
The ! prefix of commands is only for admins, and . prefix is used for players...

After update to latest action build Knife Round Vote crash stopped?

**Comment by noa1ms** [comment]
> The ! prefix of commands is only for admins, and . prefix is used for players...
> 
> After update to latest action build Knife Round Vote crash stopped?

No, she stayed, I just downloaded this build today, and compiled it ... I can throw off the IP of the server, you can see, or the file itself

**Comment by SmileYzn** [comment]
Did you can post language file? or make a request with new translation?

**Comment by Escap3d** [comment]
> Did you can try to explain better?
> I have added a votemap automatically at match end.

I want fastcup votemap cutting before match start for manual voting map cuttings for both teams..

 U add end off match its good but not recommended this option is good but dont remove..
I hope u understand

**Comment by noa1ms** [comment]
> 

yes, of course, after work I can throw off the full translation

**Comment by SmileYzn** [comment]
Someone have an video of that vote map?
I still do not understand what is cutting feature in votes 😕

**Comment by noa1ms** [comment]
I'm sorry but I don't remember either

**Comment by Escap3d** [comment]
> Someone have an video of that vote map?
> I still do not understand what is cutting feature in votes 😕


For example u have 5 maps for both team and captain of team bith is cutting captain map for 10 seconds for the last one

**Comment by SmileYzn** [comment]
I really did not understand how that happens, sorry. I need a video or more info of steps to do.

**Comment by Escap3d** [comment]
I want to fastcup map voting system pick and ban map for picking for both captain


U k ow what is fastcup??

**Comment by yuyiken** [comment]
He wants to have a pool of maps to ban by captains. Like BO3 or BO5 where captains choose maps... before start competitive.
But this mod is not designed to do that. Its not tournament managment or something like that its just pug mod, automix..
@Escap3d you should read description first about what this mod does before ask stuff like that.. If you want more personalized version, you can hire a programmer that can do this stuff for you.
