### ISSUE TITLE
2nd Half warmup player score bug....

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#110]
Can not b default player score  in 1st half then after !start the 2nd half player score its show on 2nd half warmup kills and death added on 2nd half not show 1st half score..
sorry my bad english hope u understand :(

**Comment by SmileYzn** [comment]
```
// Store team scores in scoreboard
//
// 0 Disabled
// 1 Enabled
//
// Default "1"
mb_scoreboard_team "1"

// Store player scores in scoreboard
//
// 0 Disabled
// 1 Enabled
//
// Default "1"
mb_scoreboard_player "1"
```

**Comment by Escap3d** [comment]
> // Store team scores in scoreboard
> //
> // 0 Disabled
> // 1 Enabled
> //
> // Default "1"
> mb_scoreboard_team "1"
> 
> // Store player scores in scoreboard
> //
> // 0 Disabled
> // 1 Enabled
> //
> // Default "1"
> mb_scoreboard_player "1"
![C1FD65C6-5AFE-409F-B806-EC8EAEBBE92C](https://github.com/SmileYzn/MatchBot/assets/78939962/bdae8f2e-6c4c-4cd0-a5e4-4becad962e5e)

I am saying that player score can not original score in first half aftar warmup some round playing then start the 2nd half per player score is showing is warmup score add in 2nd half..

**Comment by SmileYzn** [comment]
The real logic of scoreboard is:

1. Reset player and team scores at match start
2. Store players and team scores in first half
3. Maintain player and team scores in halftime and when second half starts
4. Maintain player and team scores at overtime and consecutives halftimes of overtime
5. Maintain player and team scores at match end

Basically, is store player and team scores at whole match in scoreboard.

What exactly is wrong here?
If you mean that halftime frags and scores is counting in scoreboard? Even after start the second half?

**Comment by SmileYzn** [comment]
Or you mean at halftime, you used !start command to start second half and messed up scores??

**Comment by Escap3d** [comment]
> Or you mean at halftime, you used !start command to start second half and messed up scores??

Yes only player score mixed up..  then start the cmd then player score is 1st hlf not minus score

**Comment by SmileYzn** [comment]
I will review it

**Comment by Escap3d** [comment]
In the second half, the player's score is getting reset, which should not happen. What I meant to say was that when halftime occurs, the warm-up time starts until the admin initiates the match. When the admin starts the match, the warm-up kills and deaths should not be added. Only the score from the first half should continue into the second half until the end of the match without any advantage or disadvantage of starting from zero. We are conducting a tournament, and we are informing you about the issues we are facing. Please don't mind.

**Comment by SmileYzn** [comment]
Try to test here for linux: https://github.com/SmileYzn/MatchBot/actions/runs/7650029001
Or here for windows: https://github.com/SmileYzn/MatchBot/actions/runs/7650029002

**Comment by Escap3d** [comment]
> Try to test here for linux: https://github.com/SmileYzn/MatchBot/actions/runs/7650029001
> Or here for windows: https://github.com/SmileYzn/MatchBot/actions/runs/7650029002

Its that fix to continue the player score in 2nd half not halftime..

**Comment by SmileYzn** [comment]
You need to store player score in halftime too? I did not understand

**Comment by Escap3d** [comment]
You need to store player score in halftime too? I did not I understand now. You are saying that the player's score should not be reset to zero in the second half. During halftime, the kills and deaths that occur during warm-up should be added, and when the second half starts, the kills and deaths in the second half should be added as well. The score from halftime should not be deducted, and the score from the first half should continue into the second half until the end of the overtime. I apologize for the confusion. I have reset the score, but I will make sure to continue the first half's score into the second half for the remaining duration of the overtime.

**Comment by SmileYzn** [comment]
Yes, it shoud be like

First Half: Nothing to do
Half Time: Normal scores, is not live
Second Half: At first round of Second half, scores are set to last scores of first half
Half Time: Normal scores, is not live (If is overtime)
Overtime: Reset scores to last scores of second half

I guess that is solved for now?

**Comment by Escap3d** [comment]
Second Half: At first round of Second half, scores are set to last scores of first half

**Comment by Escap3d** [comment]
I apologize for the misunderstanding. I understand now that the player's score should not reset to zero in the second half, and the score from halftime should not be added either. When the second half starts, the score from halftime should be set to zero, and the score from the last switch in the first half should continue into the second half. I apologize for any inconvenience caused, and I will make sure to implement this correctly for the upcoming matches.

**Comment by drakin001** [comment]
> Yes, it shoud be like
> 
> First Half: Nothing to do Half Time: Normal scores, is not live Second Half: At first round of Second half, scores are set to last scores of first half Half Time: Normal scores, is not live (If is overtime) Overtime: Reset scores to last scores of second half
> 
> I guess that is solved for now?

his trying to say this same thing

**Comment by SmileYzn** [comment]
I guess that is fixed?

Closing it
