### ISSUE TITLE
First Half Overtime issue!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#111]
Yesterday, a bug occurred after working overtime. When the overtime started, the team changed automatically. It doesn't usually happen like this; normally, the team you are on plays the first half on that side, and then there is a team switch.

**Comment by SmileYzn** [comment]
https://github.com/SmileYzn/MatchBot/blob/3c658b2d5c9b1bee4589229a009d4a68b96ed226/MatchBot/MatchBot.cpp#L600


Is Impossible to teams get swapped

**Comment by Escap3d** [comment]
> https://github.com/SmileYzn/MatchBot/blob/3c658b2d5c9b1bee4589229a009d4a68b96ed226/MatchBot/MatchBot.cpp#L600
> 
> Is Impossible to teams get swapped

we are testing again w8 for my rply :(

**Comment by SmileYzn** [comment]
Fixed in:

Linux: https://github.com/SmileYzn/MatchBot/actions/runs/7644642181
Windows: https://github.com/SmileYzn/MatchBot/actions/runs/7644642176
