### ISSUE TITLE
New Action Build Knife round Issue!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#114]
It seems that after using the "!start" command, the knife started but is not appearing in your hand.

**Comment by SmileYzn** [comment]
Did you checked item restrictions?

**Comment by SmileYzn** [comment]
I mean, try to put all zeros in mb_restrict_items

**Comment by Escap3d** [comment]
> I mean, try to put all zeros in mb_restrict_items

Where is that commands item ristrict in matchbot cfg..

**Comment by SmileYzn** [comment]
Forget it, test with new action build now

Ps. Did you have steam id? Add-me if you want

https://steamcommunity.com/id/_SmileY/

**Comment by Escap3d** [comment]
> Forget it, test with new action build now
> 
> Ps. Did you have steam id? Add-me if you want
> 
> https://steamcommunity.com/id/_SmileY/

check requst steam

**Comment by Escap3d** [comment]
Thanks its fixed on new action build :)

https://github.com/SmileYzn/MatchBot/actions/runs/7662369051

**Comment by Escap3d** [comment]
New Bug :(
the "!stop" command during a knife round, the knife is displayed in hand, but the primary weapon is not showing

**Comment by SmileYzn** [comment]
The !stop command does not reset the round when end match.

I added an sv_restart 1 command to fix that.
