### ISSUE TITLE
Suggestion:- Halftime freeze!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#115]
Yes, it is possible. If you remove the warm-up during halftime and extend the halftime freeze time to 60 seconds, the match will automatically go live after 60 seconds. This will give players extra time to plan their strategies during halftime. You can try implementing this and see if it meets your requirements.

**Comment by SmileYzn** [comment]
This can be archived using cars, nothing to doin code itself

**Comment by Escap3d** [comment]
I am not doing using cvar i want to work auto halftime in 60 second freezetime..

**Comment by SmileYzn** [comment]
Just use matchbot variables to enable timer system and remove reganedllcs variables that run warmup, also se freeze time to 60 seconds.

All of this on halftime.cfg
