### ISSUE TITLE
ScoreBoard and Player score Bug!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#116]
i am facing issues after a live match and death match: player kills not being added, and incorrect death counts (256 and 512) with the team scores not displaying on the scoreboard..

check it video

https://www.mediafire.com/file/ows3n26xe2tnnew/2024-01-27+21-35-37.mp4/file

**Comment by Escap3d** [comment]
> i am facing issues after a live match and death match: player kills not being added, and incorrect death counts (256 and 512) with the team scores not displaying on the scoreboard..
> 
> check it video
> 
> https://www.mediafire.com/file/ows3n26xe2tnnew/2024-01-27+21-35-37.mp4/file

@SmileYzn what about that?? U check it

**Comment by SmileYzn** [comment]
Any new test ou action build of today?

**Comment by Escap3d** [comment]
> Any new test ou action build of today?

Its new action build

**Comment by SmileYzn** [comment]
Sorry, i forgot to uploaad

**Comment by SmileYzn** [comment]
Try it 👍

**Comment by SmileYzn** [comment]
Any notice? I guess that bug appears in Linux only.

**Comment by Escap3d** [comment]
I am in company w8 for some hours i will tell u what is that on the mod.

**Comment by Escap3d** [comment]
New action build can not fixed player score and scordboard same bug.. 

@SmileYzn

**Comment by SmileYzn** [comment]
Tested today 01/02/2023 no bugs so far with linux and windows (And real players)

Post output of these commands:
version
meta list

If has amx mod x:
amxx version
amxx modules
amxx plugins

And server shows:
This server is protected by GameGuard

I have connected to the server without this Anti-Cheat, if player or you is using it. Please turn off to make sure that is not related with Anti cheat bug

**Comment by Escap3d** [comment]
This server can not b gameguard protected .. we are using old action build because new action build was not fixing.. 18 jan 2024.
![Uploading 5C36AE20-2907-45B2-870F-428055334B1D.png…]()

**Comment by SmileYzn** [comment]
I suggest you to disable all things that is not of MatchBOT and test it again the scoreboard

**Comment by Escap3d** [comment]
> I suggest you to disable all things that is not of MatchBOT and test it again the scoreboard

sorry bro my game server panel not working at this time.. i will try new action build tommorro.. its my sleeping time :(

**Comment by SmileYzn** [comment]
🙏 Do not worry bro, good night :P
