### ISSUE TITLE
Suggestion:- Player vote ij shorts words..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#118]
![7A89B9EA-396D-4FBA-AAA3-C7FE5F1B25D2](https://github.com/SmileYzn/MatchBot/assets/78939962/feae9d92-6bea-4ddb-9a59-81c6008159d1)

some commands are to long pls short them in vote player.. i am mention that player vote… 

.kick
.pause
.map
.restart
.stop

one more plz add saperate surrendwr team command
.surrender

**Comment by SmileYzn** [comment]
As explained before, i do not want to register a lot of commands only to do that.
Use votes / menus

Ps. If you ant to use other command like .surrender, just duplicate line of .vote command and try to put .surrender and maintain same id

Matchbot will display vote menu when type .vote or .surrender, if not i can fix to do that.
But new commands to do each small thing is out of question here.
