### ISSUE TITLE
Suggestion:- Saprate surrender Commands..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#119]
one more ask u think where is team surrender commands... i am suggest u seprate the commands for team surrender.. its easy for players.. 
![Screenshot 2024-02-01 220703](https://github.com/SmileYzn/MatchBot/assets/78939962/8e9511a7-5a7e-417e-8de3-eb4db743324a)

**Comment by SmileYzn** [comment]
Duplicated of #118
