### ISSUE TITLE
Player dmg and Hp end of round issue!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#120]
It appears that at the end of a round, the damage (DMG) and hit points (HP) are showing as zero.

[Season 17] (100 dmg | 1 hits) to (0 dmg | 0 hits) from Supremacy' (0 HP)
[Season 17] (100 dmg | 1 hits) to (0 dmg | 0 hits) from JhoNNy SinS.' (0 HP)
[Season 17] (100 dmg | 3 hits) to (0 dmg | 0 hits) from TaLhA (0 HP)

**Comment by SmileYzn** [comment]
That players are dead, something more?

**Comment by Escap3d** [comment]
I think the damage we deal to the opponent should be displayed at the end of the round, showing how much damage was inflicted and the remaining HP. Currently, it shows zero.

**Comment by SmileYzn** [comment]
What remain HP if player was dead?

**Comment by Escap3d** [comment]
0 hp 0 dgm zero i am hit that kill

**Comment by SmileYzn** [comment]
Please explain better what you want to do, and that is not a bug is an feature request.

```TEXT
// Show round stats on end
//
// 1 Show round damage in chat
// 2 Show round summary in chat
// 3 Show round damage in console
// 4 Show round summary in console
//
// Default "0"
mb_round_end_stats "0"
```

Round summary will appear at round end if you hit someone or someone hits you. Not necessary both or only damage done or damage received

**Comment by Escap3d** [comment]
2 option i am selected that the round end show stats player dmg and hp

**Comment by SmileYzn** [comment]
"(%d dmg | %d hits) to (%d dmg | %d hits) from ^3%s^1 (%d HP)"

First is damage done to other players by you, second part is damage received form other players.
Last Name and HP

I still did not understand what is wrong there
