### ISSUE TITLE
Suggestion:- Smoke, flashbang and Hegarnade..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#121]
Can it be done like when throwing smoke in front of the fire hole, the player's nickname is displayed along with "Smokegrenade," similarly for HE grenade and flashbang?

Example like this...

"Escape: fire in the hole (Smokegrenade)"
"Escape: fire in the hole (HEgrenade)"
"Escape: fire in the hole (Flashbang)"

@SmileYzn

**Comment by SmileYzn** [comment]
This is out of scope of matchbot. It is not all in one plugin
