### ISSUE TITLE
Captain mod + HLTV

### ISSUE THREAD

**Issue by F4ntik** [SmileYzn/MatchBot#122]
At the start of the distribution of commands in captain mode. There is a chance that one of the captains will be HLTV :D

**To Reproduce**
1. Need server with HLTV

Matchbot - [1.0.2] (https://github.com/SmileYzn/MatchBot/tree/1.0.2)

] rcon meta list
Currently loaded plugins:
      description      stat pend  file                        vers         src  load  unload
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.so          v1.9.0.5271  ini  Start ANY  
 [ 2] HitBox Fix       RUN   -    hitbox_fix_mm_i386.so       v1.1.4       ini  Start ANY  
 [ 3] Reunion          RUN   -    reunion_mm_i386.so          v0.1.92d     ini  Start Never
 [ 4] VoiceTranscoder  RUN   -    VoiceTranscoder.so          v2017RC5     ini  ANY   ANY  
 [ 5] Match Bot        RUN   -    matchbot_mm.so              v1.0.0       ini  ANY   ANY  
 [ 6] Accuracy Fix     RUN   -    accuracyfix_mm.so           v1.0.2       ini  ANY   ANY  
 [ 7] ReAimDetector    RUN   -    reaimdetector_amxx_i386.so  v0.2.2       pl1  ANY   Never
7 plugins, 7 running

] rcon amxx plugins
Currently loaded plugins:
       name                    version     author            file             status   
 [  1] Admin Base              1.9.0.5271  AMXX Dev Team     admin.amxx       running  
 [  2] Admin Commands          1.9.0.5271  AMXX Dev Team     admincmd.amxx    running  
 [  3] Admin Help              1.9.0.5271  AMXX Dev Team     adminhelp.amxx   running  
 [  4] Slots Reservation       1.9.0.5271  AMXX Dev Team     adminslots.amxx  running  
 [  5] Multi-Lingual System    1.9.0.5271  AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.9.0.5271  AMXX Dev Team     menufront.amxx   running  
 [  7] Commands Menu           1.9.0.5271  AMXX Dev Team     cmdmenu.amxx     running  
 [  8] Players Menu            1.9.0.5271  AMXX Dev Team     plmenu.amxx      running  
 [  9] Maps Menu               1.9.0.5271  AMXX Dev Team     mapsmenu.amxx    running  
 [ 10] Plugin Menu             1.9.0.5271  AMXX Dev Team     pluginmenu.amxx  running  
 [ 11] Admin Chat              1.9.0.5271  AMXX Dev Team     adminchat.amxx   running  
 [ 12] Anti Flood              1.9.0.5271  AMXX Dev Team     antiflood.amxx   running  
 [ 13] Admin Votes             1.9.0.5271  AMXX Dev Team     adminvote.amxx   running  
 [ 14] Pause Plugins           1.9.0.5271  AMXX Dev Team     pausecfg.amxx    running  

 [ 15] Stats Configuration     1.9.0.5271  AMXX Dev Team     statscfg.amxx    running  
 [ 16] ReAimDetector API       0.2.2       ReHLDS Team       reaimdetector.a  running  
 [ 17] HLTV AutoRecord         1.7         Dr.Aft            hltv_autorecord  running  
 [ 18] [190] DemoRecorder RBS  20.06.06    SKAJIbnEJIb       demorecorder_rb  running  
18 plugins, 18 running

 - amxx 1.10

 - slots: 12
 - Tested with real match

need to add a check for 
```#define FL_PROXY BIT(20)           // This is a spectator proxy```
in ```void CMatchCaptain::SetCaptain```

You're doing something similar in
MatchBot/MatchPlayer.cpp: Line number 76

// If is not HLTV
if (!((pEdict->v.flags & FL_PROXY) == FL_PROXY))

ps I'm a noob in programming, I can write complete nonsense

**Comment by SmileYzn** [comment]
I will check it, thanks for tip 🙏

**Comment by SmileYzn** [comment]
Fixes at
https://github.com/SmileYzn/MatchBot/actions/runs/7783489611
