### ISSUE TITLE
HLTV autorecord function

### ISSUE THREAD

**Issue by F4ntik** [SmileYzn/MatchBot#123]
It is possible to add functionality so that MatchBot gives the command to record the HLTV proxy demo?
This is how it is done in the AMXX plugin: "https://forums.alliedmods.net/showthread.php?p=994006 "
The point is to start recording the demo file at the start of the match and stopped at the end of the match. 

At the moment, I am using AMXX only for hltv_autorecord.amxx plugin.
This is necessary to save space on the server with HLTV proxy.

P.S. If possible, add a POV demo recording on the client. Also: at the start of the match on the client and at its end

**Comment by SmileYzn** [comment]
Need to implement sockets to remote hltv commands

**Comment by Escap3d** [comment]
> Need to implement sockets to remote hltv commands

Its an good idea for hltv work on matchbot add verious command on matchbot.cfg

**Comment by SmileYzn** [comment]
You can use LogAPI to do that.
I really do not want to implement such things out of scope of a real match.

Ps. For HLTV i think is beter make other metamod plugin than integrate directly into matchbot
