### ISSUE TITLE
Suggestion :- Player timeout and reconnect Restore Score...

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#125]
It is not possible to restore a player's score when they reconnect. If a player disconnects and then reconnects, their kills and deaths will be restored.

**Comment by SmileYzn** [comment]
Default CS 1.6 behavior in a real match is always required.

**Comment by Escap3d** [comment]
> Default CS 1.6 behavior in a real match is always required.

that is the part of real match bro

**Comment by SmileYzn** [comment]
Reset Player on disconnects.

It's impossible know how is a real reason for a player disconnect, player can get disconnect by timeout from server intentionally.

**Comment by Escap3d** [comment]
if u can do that than implement other wise not issue :)

**Comment by Escap3d** [comment]
> Reset Player on disconnects.
> 
> It's impossible know how is a real reason for a player disconnect, player can get disconnect by timeout from server intentionally.

The player should get back money along with the score..

**Comment by Escap3d** [comment]
If a player disconnects and then rejoins in the middle of a match, their score, kills, deaths, and money may not be restored.

If u implement that plz fix it. :(
