### ISSUE TITLE
Project dependencies

### ISSUE THREAD

**Issue by F4ntik** [SmileYzn/MatchBot#127]
You can somehow upload ready-made libraries on which the project depends, or direct links to download them. I can't try the new version of Matchbox because of the requirements:
ReHLDS version: 3.13.0.810-dev
ReGameDLL_CS version: 5.26.0.689-dev
Maybe describe it in your Discord channel or Readme.md

**Comment by SmileYzn** [comment]
Download last action build for rehlds and regamedllcs. Only master builds

**Comment by SmileYzn** [comment]
I will add on readme too
