### ISSUE TITLE
.votepause  server crashed.

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#130]
Fix the server crash caused by using the .votepause command.

**Comment by SmileYzn** [comment]
![image](https://github.com/SmileYzn/MatchBot/assets/5851851/4ef03ec8-28bb-4967-8cf4-486522d7d2c2)

Already fixed it.

**Comment by Escap3d** [comment]
Ok i am trying today because its joh time.. :(

**Comment by Escap3d** [comment]
https://www.mediafire.com/file/wfesez9g5scl2kf/2024-02-16+20-42-30.mp4/file


plzz check it video its not fixed

**Comment by SmileYzn** [comment]
Video is wrong check it

**Comment by Escap3d** [comment]
> Video is wrong check it
bro watch it again and watch clearly 
match is live

**Comment by Escap3d** [comment]
> Video is wrong check it

bro watch it again and watch clearly
match is live

**Comment by Escap3d** [comment]
Smiley brother, please watch the video again, the server is crashing. Using the votepause command...

**Comment by Escap3d** [comment]
> Video is wrong check it

https://www.mediafire.com/file/mz3zryegxgrk3ub/2024-02-17+20-59-49.mp4/file

Check it again i am new video upload here

**Comment by SmileYzn** [comment]
.votepause is crashing only without players in server.

Check if mb_player_vote_pause is 5 in matchbot.cfg or a valid int number, as i said in other issue:
Check if matchbot.cfg does not have an = (Equal symbom on mb_player_vote_pause)

That can cause crash in server

**Comment by Escap3d** [comment]
> @Escap3d
> 
> .votepause is crashing only without players in server.
> 
> Check if mb_player_vote_pause is 5 in matchbot.cfg or a valid int number, as i said in other issue: Check if matchbot.cfg does not have an = (Equal symbom on mb_player_vote_pause)
> 
> That can cause crash in server
I am set on matxhbot limite on votepause command 1

**Comment by Escap3d** [comment]
Sorry i am disturbing u .. i ane using all commands of limited us matchbot.cfg

.votepause
.voterestart
.votesurrendee
And much for player vote jus like this

**Comment by SmileYzn** [comment]
> Sorry i am disturbing u .. i ane using all commands of limited us matchbot.cfg
> 
> .votepause .voterestart .votesurrender .votekick .votemap And much for player vote jus like this

I did not understand, what this is related to crash?

**Comment by Escap3d** [comment]
> Sorry i am disturbing u .. i ane using all commands of limited us matchbot.cfg
> 
> .votepause .voterestart .votesurrender .votekick .votemap And much for player vote jus like this

I want to say that the vote commands used during a live match can be restricted to a limited number of players so that it doesn't require all players to vote. I have limited the voting in the match bot config to avoid crashes like the one that occurred with the pause command.

**Comment by SmileYzn** [comment]
Crashes occurs because of incorrect values in matchbot variables. It already been fixed .votepause and other commands.

A VOTE in matchbot requires a least 3 of 5 players or 6 of 10 players

**Comment by SmileYzn** [comment]
Issue? NO! is not.

It's not an issue, match will pause only on next round, and players are unable to cancel pause while running.

**Comment by Escap3d** [comment]
> Issue? NO! is not.
> 
> It's not an issue, match will pause only on next round, and players are unable to cancel pause while running.
u can not add .voteunpause commmand??

**Comment by F4ntik** [comment]
The current pause implementation is more like a timeout. Is the classic pause on the server not considered? Or is it not working properly?

**Comment by Escap3d** [comment]
> The current pause implementation is more like a timeout. Is the classic pause on the server not considered? Or is it not working properly?

I want to say that there should be a ".voteunpause" command, just like the ".votepause" command. If someone wants to resume the game right after the pause time ends, they can use this command, and the match should start immediately.

**Comment by SmileYzn** [comment]
TO be honest why someone will vote this? if teammate players voted to stop?

Jesus christ, it's vote, unvote, revote a lot of votes??

I already understand, but will not implement this mess

**Comment by borzaka** [comment]
Segmentation fault on `.votepause`
The settings are defaultj: `mb_player_vote_pause "5"`

Players started to type `.votepause`, and then server crashed.
