### ISSUE TITLE
.votesurrender cmd don't work!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#132]
.votesurrender 
in match live
[MS:1] Unable to use this command now.

**Comment by SmileYzn** [comment]
Check mb_player_vote_surrender on matchbot.cfg

**Comment by Escap3d** [comment]
> Check mb_player_vote_surrender on matchbot.cfg

Its already in matchbot.cfg this command.

**Comment by SmileYzn** [comment]
Sure? Check it:

https://github.com/SmileYzn/MatchBot/commit/0e1b7a9e25d2ff8e9de41bc7eab633ed96475ab7

**Comment by Escap3d** [comment]
surrender commmands work :)

1 more addtional plzz 
[MS:1] The Terrorists are winning: 10-7  can u add greeen color in socre number ?
