### ISSUE TITLE
Suggestion:- Steam id changer kick and ban!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#135]
Is it possible to add a Steam ID changer within this mod so that players who change their Steam ID and try to join the server again get automatically kicked or banned? If we want to add a command for this, can it be added to the matchbot.cfg file so that it can be toggled on or off and have an impact on the server?

**Comment by SmileYzn** [comment]
This is not what matchbot do.
To be honest these things are possible only because of non-steam if i'm right?

Non-Steam servers player is not supported by me, it's 2024 👍
