### ISSUE TITLE
server crash new action build!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#139]
A new action is causing the server to crash repeatedly, and it is not starting.

https://github.com/SmileYzn/MatchBot/actions/runs/8068926589

**Comment by SmileYzn** [comment]
Post more details about crash, i did not have a crystal ball!

**Comment by Escap3d** [comment]
"That is true, in HLDS, a crash file did not appear, I saw a debug file and this happened due to the new action build. When I reverted back to the old one, it worked fine:(

**Comment by Escap3d** [comment]
fixed on next day i dont know how :)
