### ISSUE TITLE
Not working after compiling

### ISSUE THREAD

**Issue by drakin001** [SmileYzn/MatchBot#142]
Hi, the match bot isn't working after compiling. There were some errors during compilation. Also, the file size is 1.7MB, which is larger than your release file size. 

Here's a picture of the warnings or errors: 
![Capture](https://github.com/SmileYzn/MatchBot/assets/23008063/3d82225b-ad94-4296-abdd-11a4496cf645)

**Comment by SmileYzn** [comment]
Check actions build, and Github workflow for Linux. I can't support 3rd part compilation by themselves.

**Comment by drakin001** [comment]
Sadly, Ubuntu 22 or Debian 12 no longer support GCC 4.8, which is required to compile the program. I had to install Ubuntu 18 to compile it.

**Comment by SmileYzn** [comment]
> Sadly, Ubuntu 22 or Debian 12 no longer support GCC 4.8, which is required to compile the program. I had to install Ubuntu 18 to compile it.

Whole HLDS ecosystem for linux is a mess, since it's compiled with gcc 4.8, if you compile on newest compilers, that metamod plugin wont work with oldest linux systems like CentOS 7
