### ISSUE TITLE
Server crashed..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#149]
We are using all latest plugin amx meta plugin but srver can not be run no debug file found..

**Comment by Escap3d** [comment]
@SmileYzn bro plugin not working in my server .. because server crashed

**Comment by Escap3d** [comment]
![Screenshot 2024-11-12 194808](https://github.com/user-attachments/assets/2bf7ede1-3356-4660-a8a6-74c29db262b6)
![Screenshot 2024-11-12 194745](https://github.com/user-attachments/assets/e6cda890-83bf-4256-b9fe-260740e8379a)
![Screenshot 2024-11-12 194440](https://github.com/user-attachments/assets/f8c47421-7c4a-472e-bb93-c5d562b78d96)

**Comment by Ch0wW** [comment]
Using the latest build of ReHLDS and ReGameDLL? If so, remove SafeNameAndChat ; it has no use and crashes the server.

**Comment by SmileYzn** [comment]
Before post about crashes in server, did you tested server with latest ReGameDLL + ReHLDS version without any plugin installed?

**I just can't confirm a crash without logs and with a lot of plugins installed in HLDS.**

I won't reply that type of open issues anymore.

**Comment by Escap3d** [comment]
> Before post about crashes in server, did you tested server with latest ReGameDLL + ReHLDS version without any plugin installed?
> 
> **I just can't confirm a crash without logs and with a lot of plugins installed in HLDS.**
> 
> I won't reply that type of open issues anymore.

![Screenshot 2024-11-15 141528](https://github.com/user-attachments/assets/1db37837-3e99-4fb2-b981-526a3028f652)
![Screenshot 2024-11-15 141109](https://github.com/user-attachments/assets/249f0340-4c2f-4bd3-a223-2ff1a586bf9d)



@SmileYzn  i am only on AMX, and only the MatchBot meta plugin is on, but the server is still crashing. I’m not getting the error dump file even though I wrote `-debug` in the running command and launched it.

**Comment by SmileYzn** [comment]
Did you tried with MatchBot Only?

**Comment by Escap3d** [comment]
> Did you tried with MatchBot Only?
> 

Yes this is only matchbot check not working i am share u all picture... Can u see

**Comment by SmileYzn** [comment]
@Escap3d 

![Screenshot 2024-11-15 141528](https://github.com/user-attachments/assets/1db37837-3e99-4fb2-b981-526a3028f652)

AMXX Still enabled here.

**Comment by Escap3d** [comment]
![Screenshot 2024-11-15 203041](https://github.com/user-attachments/assets/201bb9a1-1d27-425b-bf56-c96e76e74a2b)

**Comment by Escap3d** [comment]
same server crashed

**Comment by Escap3d** [comment]
I want to organize a tournament in December, and I want to check the mod once to ensure there are no bugs. Currently, there’s an issue with the server crashing, and there was another bug in the last overtime match where player scores were being reduced. That issue might still not be resolved. Please thoroughly check overtime three times to ensure that player scores and team scores are continuous and that there are no bugs.

**Comment by Ch0wW** [comment]
Sorry upping up the topic, but update metamod-r to the latest action build. I've no more crash using the latest revisions.

**Comment by Escap3d** [comment]
https://www.mediafire.com/file/p4gnm4wfyxytqqe/2024-12-16+23-48-42.mp4/file

look at this video

**Comment by Escap3d** [comment]
> https://www.mediafire.com/file/p4gnm4wfyxytqqe/2024-12-16+23-48-42.mp4/file
> 
> look at this video

@SmileYzn can u see that ?

**Comment by Escap3d** [comment]
My probl3m same not fixed. server can not run with new action release 😓

**Comment by Escap3d** [comment]
We are using debian 10 version but server crashed

**Comment by SmileYzn** [comment]
@Escap3d
Please open new issue and try to respect bug report template and i will help!
