### ISSUE TITLE
round score issue

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#15]
look round msg and scoreboard round are different show
![Screenshot (20)](https://user-images.githubusercontent.com/78939962/229181727-17c07b7e-8519-44b6-ab5a-3a278a6fc21b.png)

**Comment by SmileYzn** [comment]
Did you restarted Second Half manually?

**Comment by Escap3d** [comment]
Its affect on freezetime

**Comment by Escap3d** [comment]
> Did you restarted Second Half manually?

plz fix it msg score and scoreboard score was diferent show :(

**Comment by SmileYzn** [comment]
I won't fix it if you do not try to explain better what is the bug. I
tested many times and scores are counting normally.

I need to know what exactly is happening 🤔

Em qua., 12 de abr. de 2023 14:51, Muhammad Humza Shafique <
***@***.***> escreveu:

**Comment by Escap3d** [comment]
> I won't fix it if you do not try to explain better what is the bug. I tested many times and scores are counting normally. I need to know what exactly is happening 🤔 Em qua., 12 de abr. de 2023 14:51, Muhammad Humza Shafique < ***@***.***> escreveu:
> […](#)

Its affect on player and admin pause freezetime then happen this issue
