### ISSUE TITLE
knife round bug and sv crashed

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#16]
i was testing knife round the !start the match and i instanly !stop the knife round stop but after restart knife not switching to assault plzz fix it

https://www.veed.io/view/2adf751a-62a0-4b59-bee0-8699ed887951?sharingWidget=true&panel=share

**Comment by SmileYzn** [comment]
Fixed on latest action build, the winner team can't be calculated and match crashed.
