### ISSUE TITLE
Suggestion:-  HUD MESSEGE

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#18]
can u add HUD MEssege...

Last Round After Switching
Winner Team
OverTime Start
Knife Round Winner

**Comment by SmileYzn** [comment]
I will not put these messages, since match bot is designed to run without affect any thing on client screen.

**Comment by Escap3d** [comment]
> I will not put these messages, since match bot is designed to run without affect any thing on client screen.

[try to under stand](https://www.youtube.com/watch?v=0400GeOmQ90&ab_channel=Tochan) 

look this is fastcup match for gameguard anticheat its a good mod this mod was smooth shooting smooth brust i dont know how but its smooth
