### ISSUE TITLE
server crashes 

### ISSUE THREAD

**Issue by noa1ms** [SmileYzn/MatchBot#19]
I found a bug, after a knife round, the server crashes

**Comment by noa1ms** [comment]
Warning: failed to init SDL thread priority manager: SDL not foun

**Comment by SmileYzn** [comment]
Did you have downloaded latest action build?

**Comment by Escap3d** [comment]
> Did you have downloaded latest action build?

I think he is using old version.. i am using no crash sv

**Comment by SmileYzn** [comment]
I have fixed it yestarday, testing some times here nothing that crashed the server.

**Comment by noa1ms** [comment]
> I have fixed it yestarday, testing some times here nothing that crashed the server.

"0.0.2"

**Comment by noa1ms** [comment]
root@srvpn:/home/MatchBot-main/MatchBot# make matchbot && strip -x Release/matchbot_mm.so
g++ -I. -Iinclude/cssdk/common -Iinclude/cssdk/dlls -Iinclude/cssdk/engine -Iinclude/cssdk/game_shared -Iinclude/cssdk/pm_shared -Iinclude/cssdk/public -Iinclude/metamod -std=gnu++11 -pipe -g0 -O3 -s -flto -funroll-loops -fomit-frame-pointer -fno-stack-protector -fPIC -g -DNDEBUG -Dlinux -D__linux__ -D_GLIBCXX_USE_CXX11_ABI=0 -U_FORTIFY_SOURCE -m32 -msse3 -msse4.1 -shared *.cpp -static-libstdc++ -oRelease/matchbot_mm.so
MatchUtil.cpp: In member function ‘void CMatchUtil::ServerCommand(const char*, ...)’:
MatchUtil.cpp:290:18: warning: ‘char* strncat(char*, const char*, size_t)’ specified bound 1 equals source length [-Wstringop-overflow=]
  290 |         Q_strncat(cmd, "\n", 1);

**Comment by Escap3d** [comment]
> root@srvpn:/home/MatchBot-main/MatchBot# make matchbot && strip -x Release/matchbot_mm.so
> g++ -I. -Iinclude/cssdk/common -Iinclude/cssdk/dlls -Iinclude/cssdk/engine -Iinclude/cssdk/game_shared -Iinclude/cssdk/pm_shared -Iinclude/cssdk/public -Iinclude/metamod -std=gnu++11 -pipe -g0 -O3 -s -flto -funroll-loops -fomit-frame-pointer -fno-stack-protector -fPIC -g -DNDEBUG -Dlinux -D__linux__ -D_GLIBCXX_USE_CXX11_ABI=0 -U_FORTIFY_SOURCE -m32 -msse3 -msse4.1 -shared _.cpp -static-libstdc++ -oRelease/matchbot_mm.so MatchUtil.cpp: In member function ‘void CMatchUtil::ServerCommand(const char_, ...)’:
> MatchUtil.cpp:290:18: warning: ‘char* strncat(char*, const char*, size_t)’ specified bound 1 equals source length [-Wstringop-overflow=]
> 290 | Q_strncat(cmd, "\n", 1);

Which os r u using??

**Comment by noa1ms** [comment]
Ubuntu 20.04

**Comment by Escap3d** [comment]
> Ubuntu 20.04

https://github.com/SmileYzn/MatchBot/actions/runs/4620465575


download from here new updated much more fixes bugs

**Comment by noa1ms** [comment]
> > Ubuntu 20.04
> 
> https://github.com/SmileYzn/MatchBot/actions/runs/4620465575
> 
> download from here new updated much more fixes bugs
I downloaded it for linux, it still crashes after you select the command and wait for the server to restart

**Comment by noa1ms** [comment]
and you can tell me where to replace the command instead of "." with, for example, "/" in more detail, what would be /ready instead of .ready

**Comment by SmileYzn** [comment]
I do not recommend you to compile on linux ubuntu 20.04 with static libs. Anyway server can't just crash now for that.

See MatchCommands.cpp

Ps.
I do not will provide any support for custom releases or code changes outside github.

I will close issue
