### ISSUE TITLE
Language issue!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#2]
Hello .. i hope u r good i have language issue how can chnage ru language to english

**Comment by yuyiken** [comment]
mb_language "en"
Add this lane in matchbot.cfg 
or compile 
and change lane 10 

`this->m_Language = gMatchUtil.CvarRegister("mb_language", "bp"); to 
this->m_Language = gMatchUtil.CvarRegister("mb_language", "en");`

**Comment by Escap3d** [comment]
> Hi @Escap3d Add this lane in matchbot.cfg mb_language "en" or compile and change lane 10 in MatchLanguage.cpp `this->m_Language = gMatchUtil.CvarRegister("mb_language", "bp"); to this->m_Language = gMatchUtil.CvarRegister("mb_language", "en");`

do u know auther name (smiley) like this build ???

**Comment by SmileYzn** [comment]
Please do the correct things :rofl:

1. Open addons/matcobot/cfg/matchbot.cfg
2. CHANGE mb_language "en" to mb_language "ru" (Change variable instead of add!)
3. Add missing sentences for russian "ru" translations in addons/matchbot/language.txt
4.
For example in every sentence where is:

```"You do not have access to that command."
en:"You do not have access to that command."
bp:"Você não tem acesso a esse comando."```

Add ru: (Russian)


```"You do not have access to that command."
en:"You do not have access to that command."
bp:"Você não tem acesso a esse comando."
ru:"У вас нет доступа к этой команде."```

If you missing any russioan sentence to translate, the server will display in default  language (English).

Please: Note that language.txt is UTF-8 File without BOM

**Comment by Escap3d** [comment]
> Please do the correct things 🤣
> 
> 1. Open addons/matcobot/cfg/matchbot.cfg
> 2. CHANGE mb_language "en" to mb_language "ru" (Change variable instead of add!)
> 3. Add missing sentences for russian "ru" translations in addons/matchbot/language.txt
> 
> For example in every sentence where is:
> 
> ```
> en:"You do not have access to that command."
> bp:"Você não tem acesso a esse comando."```
> 
> Add ru: (Russian)
> 
> 
> ```"You do not have access to that command."
> en:"You do not have access to that command."
> bp:"Você não tem acesso a esse comando."
> ru:"У вас нет доступа к этой команде."```
> 
> If you missing any russioan sentence to translate, the server will display in default  language (English).
> 
> Please: Note that language.txt is UTF-8 File without BOM
> ```

How cAn i change ur name after connected the game show ur nick (smiley) i want it plzz tell where is file can i edit..

**Comment by SmileYzn** [comment]
Why? I did not understand, you can write without a translator?

**Comment by yuyiken** [comment]
He want to delete they saytext that appears with build date and (your nickname) when someone joins to the server.

**Comment by SmileYzn** [comment]
@yuyiken Thanks

If @Escap3d wants something else, make a new build for it!

That is know as remove credits of author, the MatchBOT project is open source. Anyone is free to change it :+1: 

Issue is closed for now

**Comment by Escap3d** [comment]
> @yuyiken Thanks
> 
> If @Escap3d wants something else, make a new build for it!
> 
> That is know as remove credits of author, the MatchBOT project is open source. Anyone is free to change it 👍
> 
> Issue is closed for now

Can u lacate where is it?
