### ISSUE TITLE
suggestion to improve the chat

### ISSUE THREAD

**Issue by noa1ms** [SmileYzn/MatchBot#20]
I have a suggestion, instead of a message in a chat like Terrorists are winning: 15-0, to make it more beautiful like Terrorists (15) - (0) Counter-Terrorists so that each round would be displayed like this....... 

also en:"Game Over! The \3%s\1 have won the game: %d-%d"  
Make Side A(16) - (2) Side B

**Comment by SmileYzn** [comment]
I will implement a parser to score messages i.e:

"{TeamTR} ({ScoreTR}) - ({ScoreCT}) {TeamCT}"

TeamTR: Name of Terrorists
TeamCT: Name of CTs
ScoreTR: Score of Terrorists
ScoreCT: Score of CTs
Winner: Name of winner team
Scores: Both scores like %d-%d 8x7 for example, starting with higest winner score

With that you can implement it on language.txt

**Comment by Escap3d** [comment]
> I will implement a parser to score messages i.e:
> 
> "{TeamTR} ({ScoreTR}) - ({ScoreCT}) {TeamCT}"
> 
> TeamTR: Name of Terrorists TeamCT: Name of CTs ScoreTR: Score of Terrorists ScoreCT: Score of CTs Winner: Name of winner team Scores: Both scores like %d-%d 8x7 for example, starting with higest winner score
> 
> With that you can implement it on language.txt

add in CT blue color and TT RED COlor

**Comment by SmileYzn** [comment]
Only one color of team is allowed in chat, it is impossible use red and blue at same chat msg.
Of course, you can use other colors along with one color of team.

This request was fixed with this variable at matchbot.cfg

```
// Scores display method
//
// 0 Default scores with phrases
// 1 Show all teams and scores
//
// Default "0"
mb_score_type "0"
```

If someone want to change phrases, go to language.txt and edit the score messages
