### ISSUE TITLE
Knife round bug! to !stop Warmup!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#22]
I have another problem with the knife Round an i !stop If I turn it off, the knife remains on the hand, warm-up mode, so it seems that there is not Assault show in my hand sometime i am switching so only knife in my hand... then i was change the map warmup was normal work..

u check it in ur server

plz fix it  :(

**Comment by SmileYzn** [comment]
Fixed on [1e62ccb](https://github.com/SmileYzn/MatchBot/commit/1e62ccbb0f934ebe3641618b72622fd65d45c097)
