### ISSUE TITLE
smoke issue..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#23]
The use of gameguard anticheat plugin while the matchbot mod is active the smoke bugs out and it is more thick dark and denser and causes frame drops

**Comment by SmileYzn** [comment]
MatchBOT do not touch on engine things like smoke. 

And I do not provide support for other plugins than MatchBOT.

I suggest you to contact author of that plugin to see what is wrong

**Comment by yuyiken** [comment]
@Escap3d As far as I know gameguard is Fastcup anticheat system. If you play cs with it you will have dense smoke on all servers include ur private one. This effect is doing the anticheat system. This actually is nothing related to matchbot @SmileYzn you should close it.

**Comment by Escap3d** [comment]
> @Escap3d As far as I know gameguard is Fastcup anticheat system. If you play cs with it you will have dense smoke on all servers include ur private one. This effect is doing the anticheat system. This actually is nothing related to matchbot @SmileYzn you should close this "issue"

I know but gameguard smoke different but not fastcup smoke in this situation intesity to much dark smoke my teammate says this is not gameguard smoke 🥲

**Comment by SmileYzn** [comment]
Again, MatchBOT do not touch on engine things. Is impossible to fix a thing that is not part of this plugin.

**Comment by Escap3d** [comment]
> Again, MatchBOT do not touch on engine things. Is impossible to fix a thing that is not part of this plugin.

I am using rehlds version 3.13.783 this is action build but i am can not install official release dev 3.12.780 version in github
