### ISSUE TITLE
Suggestion to change the chat message

### ISSUE THREAD

**Issue by noa1ms** [SmileYzn/MatchBot#24]
I want to suggest changing the chat message from "The "Teams are TeamB" are winning: %d-%d" for example to "The are winning: "TeamA" "score" : "TeamB" "score" " I think it would be more correct.... and this whole method

**Comment by noa1ms** [comment]
you can close it, I've already done it myself

**Comment by SmileYzn** [comment]
If you name teams, do not forget to do all the login when game changes.
