### ISSUE TITLE
Suggestion:- Tectical Timeout Player Pause..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#26]
https://forums.alliedmods.net/showthread.php?t=339686

@SmileYzn you learn this and add this per team timeout pause allowed 2 CT and TT and unpause timeout allowed to 3 time per map

**Comment by Escap3d** [comment]
@SmileYzn this is fastucp pause mod its a good for Torni useable for this pause plzz implement in this mod

**Comment by noa1ms** [comment]
it's good idea 💡

**Comment by Escap3d** [comment]
i think smiley not intested :(

**Comment by Escap3d** [comment]
@yuyiken

**Comment by yuyiken** [comment]
@Escap3d you actually have a .vote and can vote pause.

**Comment by Escap3d** [comment]
Pause round for limited uses for per team 2 times for per team.. who can get pause time like ct and tt shoe client msg and hud msg
