### ISSUE TITLE
Issue mb_help_file!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#27]
this file cannot show player cmd .help and admin cmd !help white blank html show...

![Screenshot (30)](https://user-images.githubusercontent.com/78939962/230782171-ce3c0770-fe3e-46d0-93d7-ed78fa9afdc5.png)

**Comment by noa1ms** [comment]
need web site http://help.srvpn.ru/user_help.html

**Comment by SmileYzn** [comment]
> need web site http://help.srvpn.ru/users_help.html

Is not needed, file users_help.html exists on matchbot folder? and server can read it??

**Comment by noa1ms** [comment]
yes, I have it in this folder, but he doesn't want to read something

**Comment by SmileYzn** [comment]
It will be fixed here:

https://github.com/SmileYzn/MatchBot/actions/runs/4659643147

Wait compilation run and generate artifacts
