### ISSUE TITLE
About the startup error and inexplicable restart problem

### ISSUE THREAD

**Issue by tarimren-admin** [SmileYzn/MatchBot#28]
The server environment is as follows:
1、windows 2016 datacenter server.
2, HLDS: 8684 updated via SteamCMD.
3、ReHLDS：3.12.0.780.
4、ReGameDLL：5.21.0.576
5、metamod：1.3.0.131
The components running are as follows:
1、SafeNameAndChat：1.2 Beta3
2、Reunion：0.1.92d
3、Rechecker：2.7
4、WHBlocker：1.5.697
5、Match Bot：0.02
Run the prompt as follows:

Metamod-r v1.3.0.131, API (5:13)
Metamod-r build: 18:51:29 Jul 11 2022
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/adc9414
[WHB] Version: 1.5.697 Windows (Usage SSE 4.1)
[WHB] Success: Build ReHLDS version defined Windows '3082'
[WHB] Success: Configuration executed.
[BOT] ReHLDS API minor version mismatch; expected at least 13, real 12
[BOT] Please update the ReHLDS up to a minor version API >= 13
[BOT] Re-GameDLL API successfully initialized.
ReGameDLL version: 5.21.0.576-dev
Navigation map loaded.

After the server starts, it will reboot from time to time.

**Comment by SmileYzn** [comment]
Error is clear, update rehlds and regamedll_cs versions

Em qua., 12 de abr. de 2023 23:10, tarimren-admin ***@***.***>
escreveu:

**Comment by tarimren-admin** [comment]
Thank you for your reply
But I'm using ReHLDS version 3.12.0.780 and ReGameDLL version 5.21.0.576, both are already up to date.

**Comment by SmileYzn** [comment]
Rehlds is in 3.13 api, plugin Works for other users, why I should expect
that server is updated?

Em qui., 13 de abr. de 2023 22:52, tarimren-admin ***@***.***>
escreveu:

**Comment by SmileYzn** [comment]
Did you made a custom build?

Em sex., 14 de abr. de 2023 08:40, Cleverson Souza ***@***.***>
escreveu:

**Comment by SmileYzn** [comment]
@tarimren-admin 

We always need to use actions build from rehlds team, since this repository has a delayed launch of releases.

Download ReHLDS from here:
https://github.com/dreamstalker/rehlds/actions/runs/4148646870

appversion.h

```
#ifndef __APPVERSION_H__
#define __APPVERSION_H__

//
// This file is generated automatically.
// Don't edit it.
//

// Version defines
#define APP_VERSION "3.13.0.783-dev"
#define APP_VERSION_C 3,13,0,783
#define APP_VERSION_STRD "3.13.0.783"
#define APP_VERSION_FLAGS 0x0L

#define APP_COMMIT_DATE "Feb 11 2023"
#define APP_COMMIT_TIME "00:05:02"

#define APP_COMMIT_SHA "1796459"
#define APP_COMMIT_URL "https://github.com/dreamstalker/rehlds/commit/"

#endif //__APPVERSION_H__
```

Also need to do same with regamedll_cs, Update to latest action build from master branch

https://github.com/s1lentq/ReGameDLL_CS/actions/runs/4600485694
