### ISSUE TITLE
Overtime player score issue

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#31]
When the overtime were shown, the player score was the same as when the second overtime start then player score was 0...

**Comment by Escap3d** [comment]
No one check this??

**Comment by noa1ms** [comment]
check I

**Comment by SmileYzn** [comment]
I will fix all things related to scoreboard 👍

**Comment by Escap3d** [comment]
> I will fix all things related to scoreboard 👍

Where is action build?

**Comment by Escap3d** [comment]
> I will fix all things related to scoreboard 👍

overtime start then player score was second half show why score is show player is second half player score not maintain when over time start...

**Comment by Escap3d** [comment]
> I will fix all things related to scoreboard 👍

EID MUBARAK BRO :)

**Comment by SmileYzn** [comment]
I hope that is fixed with https://github.com/SmileYzn/MatchBot/commit/6316185f037394c1d9d59c01719708209394e3f6
