### ISSUE TITLE
Suggestion:- auto ready.

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#37]
Can u add auto ready system in this mod for automix

**Comment by yuyiken** [comment]
Hello, you have a timer when all players are on the server you can setup timer for ready game, default is 60 sec. Check matbot.cfg config.

**Comment by Escap3d** [comment]
> Hello, you have a timer when all players are on the server you can setup timer for ready game, default is 60 sec. Check matbot.cfg config.

This is not auto ready this time for player get write .ready to play for mix

**Comment by yuyiken** [comment]
`// Ready System Type
// If disabled, match need to be started by an administrator
//
// 0 Disabled
// 1 Ready System
// 2 Ready Timer
//
// Default "1"
mb_ready_type "2"

// Ready System timer delay in seconds
// Works if Ready System type is 2
//
// Default "60.0"
mb_ready_time "20.0"`

I'm testing with this system 
mb_ready_type 2 
This start automix when all 10 person is in the server and then 
mb_ready_time runs back to 0 and autostarts.
