### ISSUE TITLE
halftime after switching issue!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#38]
how to stop halftime we are playing the team are swtched then halftime start why? any cmd stop this

**Comment by Escap3d** [comment]
How can i getout for hAlftime 😔

**Comment by Escap3d** [comment]
how can i stop halftime in 2nd half any cmd ??? @SmileYzn

**Comment by SmileYzn** [comment]
Just use automatic ready system, what exactly you trying to do?

**Comment by Escap3d** [comment]
> Just use automatic ready system, what exactly you trying to do?

I am only using manualy cmds and mix match not pug just like torni match 🙂

**Comment by SmileYzn** [comment]
Did you want to run match bot only using commands?

**Comment by SmileYzn** [comment]
Fixed in https://github.com/SmileYzn/MatchBot/actions/runs/4838951899
