### ISSUE TITLE
suggestion site match bot

### ISSUE THREAD

**Issue by noa1ms** [SmileYzn/MatchBot#39]
I can make a website for match bot servers, if you are interested, I can provide a demo as I see it.

**Comment by SmileYzn** [comment]
I already have it, it will launch soon 🙏 

https://pugbr.net/

![image](https://user-images.githubusercontent.com/5851851/235150010-86c38e93-74a4-4b64-88a7-991d4f379f06.png)

![image](https://user-images.githubusercontent.com/5851851/235150238-df35458c-7690-45b2-b58f-503da10abbd3.png)

![image](https://user-images.githubusercontent.com/5851851/235150370-95f2da2a-b2d7-4643-9794-ecc81779a8ab.png)

Project is not dead, i only afk for these days duo my work. 
I can't work on matchbot in peace as i need on poject 🙏

**Comment by noa1ms** [comment]
> I already have it, it will launch soon 🙏
> 
> https://pugbr.net/
> 
> ![image](https://user-images.githubusercontent.com/5851851/235150010-86c38e93-74a4-4b64-88a7-991d4f379f06.png)
> 
> ![image](https://user-images.githubusercontent.com/5851851/235150238-df35458c-7690-45b2-b58f-503da10abbd3.png)
> 
> ![image](https://user-images.githubusercontent.com/5851851/235150370-95f2da2a-b2d7-4643-9794-ecc81779a8ab.png)
> 
> Project is not dead, i only afk for these days duo my work. I can't work on matchbot in peace as i need on poject 🙏

ugh, it looks really cool, honestly I like this site

**Comment by SmileYzn** [comment]
Thanks :pray: 

When site is open, i will post something here :+1:
