### ISSUE TITLE
Need help for matchbot mod

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#4]
Can i manual oprate this mod yes or not then yes tell me commands to manual oprate… i want to use competitive match making server

**Comment by yuyiken** [comment]
Hi, yes you can. First you need is be an admin. 
edit /cstrike/addons/matchbot
/admin.ini
and add 
"YOURSTEAMIDHERE"	"Name"	"abcdefghijklmnopqrstuvy"

Then go to your server and type !menu and choose (6) Control Match
Now you are able to start stop etc..

**Comment by SmileYzn** [comment]
MatchBOT lack documentation of features. I will provide it soon
