### ISSUE TITLE
Ready check/list

### ISSUE THREAD

**Issue by Gawnz1** [SmileYzn/MatchBot#40]
Hello, is it possible to make a addition to the ready system:
Add one more HudMessage with status if you are ready or not
To print You are ready/You are not ready on the HudMessage List?

Also a ready list (open a motd) with command would be also good, because some people play with very low resolutions and they can't see the list

**Comment by yuyiken** [comment]
Hello @Gawnz1, I dont think this will be done. 
Try forking the project and comment Line 73 and Line 75 in MatchReady.cpp

**Comment by Gawnz1** [comment]
Hello, thanks for the answer.
I can comment them, but how can I print a personal message to the client with his ready status, so the player itself to know if he is typed ready or not?

**Comment by SmileYzn** [comment]
@Gawnz1

The ready system already has a hud message to see if you is ready or not, did you can try to explain better or draw a imagem with what you want to do?

And abour resolution, even in 640x480 players can see the hudmessages, what is the problem??

About MOTD, i avoid to open things on clients, to prevent spam

**Comment by Gawnz1** [comment]
It displays your current name in ready/not ready column. 

I want to add a one custom and simple personal player->edict() hudmessage with the player ready status (You are ready/You are not ready)

About the low resolution: What about if we move it from the top? Customize it by our own taste I mean, not everyone will be able to see it if we put it under the radar for example.

The motd - What's the spam? To open a personal motd like the .help command?

**Comment by SmileYzn** [comment]
@Gawnz1

I test in 640x480 and do not see any problem with hud list message.
Do not make sense add a new message to player telling he is ready if he already in read list.

![image](https://user-images.githubusercontent.com/5851851/235278977-9524b9a4-221f-4f80-8810-af36fd24f19b.png)

About motd, again i will not show it to player. For that already have default CS MOTD when player comes to server, if you want you can put all information about pug here, and already have a chat message telling the player can do, like use .help or use .ready command.

Or even better of all this, you can use automatic ready system by timer before match starts.

I need to maintain MatchBot clear at all

**Comment by Gawnz1** [comment]
Nevermind. I will try to add it by myself. Sorry for taking some of your time. I really appreciate the answers and the time you spend on my issue.
