### ISSUE TITLE
I can provide Chinese translation of lang

### ISSUE THREAD

**Issue by tarimren-admin** [SmileYzn/MatchBot#43]
"Dead"
en:"Dead"
bp:"Nenhum"
cn:"死亡"

"Warmup"
en:"Warmup"
bp:"Aquecimento"
cn:"热身模式"

"Starting"
en:"Starting"
bp:"Inciando"
cn:"开始"

"First Half"
en:"First Half"
bp:"Primero Tempo"
cn:"上半场比赛"

"Half Time"
en:"Half Time"
bp:"Intervalo"
cn:"中场休息"

"Second Half"
en:"Second Half"
bp:"Segundo Tempo"
cn:"下半场比赛"

"Overtime"
en:"Overtime"
bp:"Overtime"
cn:"加时赛"

"Finished"
en:"Finished"
bp:"Finalizado"
cn:"结束"

"Unassigned"
en:"Unassigned"
bp:"Unassigned"
cn:"尚未分配"

"Terrorists"
en:"Terrorists"
bp:"Terroristas"
cn:"恐怖分子"

"Counter-Terrorists"
en:"Counter-Terrorists"
bp:"Countra-Terroristas"
cn:"反恐精英"

"Spectators"
en:"Spectators"
bp:"Espectadores"
cn:"观众"

"NONE"
en:"NONE"
bp:"NENHUM"
cn:"无"

"TR"
en:"TR"
bp:"TR"
cn:"匪徒"

"CT"
en:"CT"
bp:"CT"
cn:"警察"

"SPEC"
en:"SPEC"
bp:"SPEC"
cn:"观众"

"Team Player"
en:"Team Player"
bp:"Time do jogador"
cn:"队员"

"You do not have access to that command."
en:"You do not have access to that command."
bp:"Você não tem acesso a esse comando."
cn:"你没有使用使用该命令的权限."

"Match BOT Menu"
en:"Match BOT Menu"
bp:"Match BOT Menu"
cn:"比赛BOT菜单"

"Kick Player"
en:"Kick Player"
bp:"Kickar Jogador"
cn:"踢出玩家"

"Ban Player"
en:"Ban Player"
bp:"Banir Jogador"
cn:"封禁玩家"

"Slay Player"
en:"Slay Player"
bp:"Matar Jogador"
cn:"处死玩家"

"Change Map"
en:"Change Map"
bp:"Mudar Mapa"
cn:"更换地图"

"Match Control"
en:"Match Control"
bp:"Controlar Partida"
cn:"比赛控制"

"Send Message"
en:"Send Message"
bp:"Enviar Mensagem"
cn:"发送消息"

"Send Command"
en:"Send Command"
bp:"Enviar Comando"
cn:"发送命令"

"Swap Teams"
en:"Swap Teams"
bp:"Trocar Times"
cn:"交换队伍"

"Choose a time to ban: \\w%s\\y"
en:"Choose a time to ban: \\w%s\\y"
bp:"Escolha o tempo para banir: \\w%s\\y"
cn:"选择封禁时长: \\w%s\\y"

"Change Team"
en:"Change Team"
bp:"Mudar Time"
cn:"变更队伍"

"Set \\w%s\\y Team"
en:"Set \\w%s\\y Team"
bp:"Mudar Time: \\w%s\\y"
cn:"设置 \\w%s\\y 队伍"

"\3%s\1 changed map to: \4%s\1..."
en:"\3%s\1 changed map to: \4%s\1..."
bp:"\3%s\1 mudou o mapa para: \4%s\1..."
cn:"\3%s\1 更换了地图: \4%s\1..."

"Run Vote Map"
en:"Run Vote Map"
bp:"Executar Vote Map"
cn:"开启地图投票"

"Run Vote Teams"
en:"Run Vote Teams"
bp:"Executar Escolha dos times"
cn:"开启队伍投票"

"Continue Match"
en:"Continue Match"
bp:"Continuar Partida"
cn:"继续比赛"

"Start Match"
en:"Start Match"
bp:"Iniciar Partida"
cn:"开始比赛"

"Stop Match"
en:"Stop Match"
bp:"Parar Partida"
cn:"停止比赛"

"Restart Match"
en:"Restart Match"
bp:"Reiniciar Match"
cn:"重新开始比赛"

"Pause Match"
en:"Pause Match"
bp:"Pausar Partida"
cn:"暂停比赛"

"Toggle Match BOT"
en:"Toggle Match BOT"
bp:"Alterar Match BOT"
cn:"切换匹配BOT"

"\3(%s)\1: %s"
en:"\3(%s)\1: %s"
bp:"\3(%s)\1: %s"
cn:"\3(%s)\1: %s"

"Usage: !msg \3<Text Message>\1"
en:"Usage: !msg \3<Text Message>\1"
bp:"Uso: !msg \3<Mensagem>\1"
cn:"用法: !msg \3<Text Message>\1"

"These commands are protected here, only \3Server\1 can use."
en:"These commands are protected here, only \3Server\1 can use."
bp:"Comando protegido, apenas o \3Servidor\1 pode usar."
cn:"这些命令受到保护, 仅 \3服务器\1 方可使用."

"\3Executed\1: %s"
en:"\3Executed\1: %s"
bp:"\3Executou\1: %s"
cn:"\3已执行\1: %s"

"Usage: !cmd \3<Server Command>\1"
en:"Usage: !cmd \3<Server Command>\1"
bp:"Uso: !cmd \3<Commando de Servidor>\1"
cn:"用法: !cmd \3<Server Command>\1"

"\3%s\1 changed team sides manually."
en:"\3%s\1 changed team sides manually."
bp:"\3%s\1 mudou os times manualmente."
cn:"\3%s\1 手动改变团队阵容."

"Can only swap teams during \4%s\1 period."
en:"Can only swap teams during \4%s\1 period."
bp:"Pode mudar os times apenas no período \4%s\1."
cn:"只能在 \4%s\1 期间交换队伍."

"Starting \4%s\1, Get Ready!"
en:"Starting \4%s\1, Get Ready!"
bp:"Iniciando \4%s\1, Fique Atento!"
cn:"开始 \4%s\1, 准备就绪!"

"Knife Round"
en:"Knife Round"
bp:"Round Faca"
cn:"拼刀局"

"Knife Round Enabled"
en:"Knife Round Enabled"
bp:"Round Faca Habilitado"
cn:"启动拼刀局"

"Starting \4Knife Round\1, Get Ready!"
en:"Starting \4Knife Round\1, Get Ready!"
bp:"Iniciando \4Knife Round\1, Fique Atento!"
cn:"开始 \4拼刀局\1, 准备就绪!"

"\3%s\1 started, Get Ready!"
en:"\3%s\1 started, Get Ready!"
bp:"\3%s\1 iniciado, Fique Atento!"
cn:"\3%s\1 开始, 做好准备!"

"Changing teams automatically."
en:"Changing teams automatically."
bp:"Trocando times automaticamente."
cn:"自动换队."

"Server is full."
en:"Server is full."
bp:"Servidor cheio."
cn:"服务器满员."

"\3Auto Team Select\1 is not allowed."
en:"\3Auto Team Select\1 is not allowed."
bp:"\3Auto Seleção\1 não permitida."
cn:"\3不允许\1 自动选队."

"\3%s\1 are not allowed."
en:"\3%s\1 are not allowed."
bp:"\3%s\1 não é permitido."
cn:"\3%s\1 不允许."

"You are already on the \3%s\1 team."
en:"You are already on the \3%s\1 team."
bp:"Você já está no time \3%s\1."
cn:"你已经加入 \3%s\1 队伍."

"Cannot switch when the game is started."
en:"Cannot switch when the game is started."
bp:"Não é possível mudar de time no meio da partida."
cn:"游戏开始无法切换."

"The \3%s\1 team is complete."
en:"The \3%s\1 team is complete."
bp:"O time \3%s\1 está completo."
cn:"\3%s\1 队伍已组建完毕."

"%s Build %s (\3%s\1)"
en:"%s Build %s (\3%s\1)"
bp:"%s Versão %s (\3%s\1)"
cn1:"%s 组建 %s (\3%s\1)"
cn:"服务器构建：毛毛的老公"

"Say \4.help\1 to view command list."
en:"Say \4.help\1 to view command list."
bp:"Say \4.help\1 para ver a lista de comandos."
cn:"Say \4.help\1 查看命令列表."

"\3%s\1: Players %d, (%d Required of %d Allowed)"
en:"\3%s\1: Players %d, (%d Required of %d Allowed)"
bp:"\3%s\1: Jogadores %d, (%d Requeridos de %d Permitidos)"
cn:"\3%s\1: 玩家 %d, (%d 需要 %d 同意)"

"\3%s\1 (\4%d\1) - (\4%d\1) \3%s\1"
en:"\3%s\1 (\4%d\1) - (\4%d\1) \3%s\1"
bp:"\3%s\1 (\4%d\1) - (\4%d\1) \3%s\1"
cn:"\3%s\1 (\4%d\1) - (\4%d\1) \3%s\1"

"Game Over: \3%s\1 (\4%d\1) - (\4%d\1) \3%s\1"
en:"Game Over: \3%s\1 (\4%d\1) - (\4%d\1) \3%s\1"
bp:"Fim de Jogo: \3%s\1 (\4%d\1) - (\4%d\1) \3%s\1"
cn:"比赛结束: \3%s\1 (\4%d\1) - (\4%d\1) \3%s\1"

"Game Over! The \3%s\1 have won the game: %d-%d"
en:"Game Over! The \3%s\1 have won the game: %d-%d"
bp:"Fim de Jogo! Os \3%s\1 venceram: %d-%d"
cn:"比赛结束! The \3%s\1 赢得比赛.比分|: %d-%d"

"The \3%s\1 are winning: %d-%d"
en:"The \3%s\1 are winning: %d-%d"
bp:"Os \3%s\1 estão vencendo: %d-%d"
cn:" \3%s\1 获胜.比分|: %d-%d"

"Game Over! Score is tied: %d-%d"
en:"Game Over! Score is tied: %d-%d"
bp:"Fim de Jogo! Placar empatado: %d-%d"
cn:"比赛结束! 平局: %d-%d"

"Score is tied: %d-%d"
en:"Score is tied: %d-%d"
bp:"Placar empatado: %d-%d"
cn:"平局: %d-%d"

"* Round %d won by: %s"
en:"* Round %d won by: %s"
bp:"* Round %d ganho por: %s"
cn:"* 第 %d 回合获胜方是: %s"

"Cannot start an vote in \3%s\1 state."
en:"Cannot start an vote in \3%s\1 state."
bp:"Não é possível votar no estado \3%s\1."
cn:"无法在 \3%s\1 状态下发起投票."

"\3%s\1 started match."
en:"\3%s\1 started match."
bp:"\3%s\1 iniciou a partida."
cn:"\3%s\1 开始比赛."

"Cannot start match in \3%s\1 state."
en:"Cannot start match in \3%s\1 state."
bp:"Não é possível iniciar a partida no estado \3%s\1."
cn:"无法在 \3%s\1 状态下进行比赛."

"\3%s\1 stopped match."
en:"\3%s\1 stopped match."
bp:"\3%s\1 parou a partida."
cn:"\3%s\1 停止比赛."

"Cannot stop match in \3%s\1 state."
en:"Cannot stop match in \3%s\1 state."
bp:"Não é possível parar a partida no estado \3%s\1."
cn:"无法在 \3%s\1 状态下停止比赛."

"\3%s\1 restarted %s, get ready!"
en:"\3%s\1 restarted %s, get ready!"
bp:"\3%s\1 reiniciou o %s, fique atento!"
cn:"\3%s\1 重启 %s, 做好准备!"

"Cannot restart match in \3%s\1 state."
en:"Cannot restart match in \3%s\1 state."
bp:"Não é possível reiniciar a partida no estado \3%s\1."
cn:"无法在 \3%s\1 状态下重启比赛."

"The choice of the teams failed: \3Not enough players.\1"
en:"The choice of the teams failed: \3Not enough players.\1"
bp:"A escolha dos times falhou: \3Faltam jogadores.\1"
cn:"选队失败: \3人数不足.\1"

"The \3%s\1 captain is: %s"
en:"The \3%s\1 captain is: %s"
bp:"O capitão do time \3%s\1: %s"
cn:"\3%s\1 的队长是: %s"

"\3%s\1 choosed \3%s\1"
en:"\3%s\1 choosed \3%s\1"
bp:"\3%s\1 escolheu \3%s\1"
cn:"\3%s\1 已选择 \3%s\1"

" (C) *"
en:" (C) *"
bp:" (C) *"
cn:" (C) *"

" (C)"
en:" (C)"
bp:" (C)"
cn:" (C)"

"Live in three restarts! \3Get Ready!!"
en:"Live in three restarts! \3Get Ready!!"
bp:"Valendo em três restarts! \3Fique Atento!!"
cn:"刷新三次开始比赛! \3请做好准备!!"

"--- MATCH IS LIVE ---"
en:"--- MATCH IS LIVE ---"
bp:"--- MATCH IS LIVE ---"
cn:"--- MATCH IS LIVE ---"

"\4Match Is Live! Good Luck & Have Fun!!"
en:"\4Match Is Live! Good Luck & Have Fun!!"
bp:"\4Match Is Live! Good Luck & Have Fun!!"
cn:"\4比赛开始! Good Luck & Have Fun!!"

"\3%s\1 Paused Match: Game will pause on next round start."
en:"\3%s\1 Paused Match: Game will pause on next round start."
bp:"\3%s\1 Pausou a Partida: O jogo vai pausar no próximo round."
cn:"\3%s\1 暂停比赛: 比赛将在下回合开始时暂停."

"Match will pause on next round start."
en:"Match will pause on next round start."
bp:"A partida será pausada no próximo round."
cn:"比赛将在下回合开始时暂停."

"Cannot pause match in freeze time period."
en:"Cannot pause match in freeze time period."
bp:"Não é possível pausar a partida no freezetime."
cn:"冻结时段无法暂停."

"Cannot pause match in \3%s\1 state."
en:"Cannot pause match in \3%s\1 state."
bp:"Não é possível pausar a partida no estado \3%s\1."
cn:"不能在 \3%s\1 状态下暂停比赛."

"Match paused: Match will continue in \3%s\1."
en:"Match paused: Match will continue in \3%s\1."
bp:"Partida Pausada: O jogo vai recomeçar em \3%s\1."
cn:"比赛暂停: 将在 \3%s\1 秒后继续进行."

"MATCH PAUSED\n%s LEFT"
en:"MATCH PAUSED\n%s LEFT"
bp:"JOGO PAUSADO\n%s RESTANTES"
cn:"比赛暂停.暂停时间剩余 \n%s 秒"

"Say \4.ready\1 to continue."
en:"Say \4.ready\1 to continue."
bp:"Say \4.ready\1 para continuar."
cn:"Say \4.ready\1 继续."

"All players are ready!"
en:"All players are ready!"
bp:"Todos os jogadores estão prontos!"
cn:"所有玩家已做好准备!"

"Not Ready (%d of %d):"
en:"Not Ready (%d of %d):"
bp:"Aquecendo (%d de %d):"
cn:"尚未准备 【%d人|队员：%d人】-|"

"Ready (%d of %d):"
en:"Ready (%d of %d):"
bp:"Prontos (%d de %d):"
cn:"|-准备就绪 【%d人|队员：%d人】"

"\3%s\1 is ready."
en:"\3%s\1 is ready."
bp:"\3%s\1 está pronto."
cn:"\3%s\1 已做好准备."

"Unable to use this command now."
en:"Unable to use this command now."
bp:"Impossível usar esse comando agora."
cn:"现在无法使用此命令."

"\3%s\1 is not ready."
en:"\3%s\1 is not ready."
bp:"\3%s\1 não está pronto."
cn:"\3%s\1 尚未准备好."

"\3%s\1 with %d HP (%d AP)"
en:"\3%s\1 with %d HP (%d AP)"
bp:"\3%s\1 tem %d HP (%d AP)"
cn:"\3%s\1 还有 %d HP (%d AP)"

"No one is alive."
en:"No one is alive."
bp:"Ninguém está vivo."
cn:"无人生还."

"Hit \3%s\1 %d time(s) (Damage %d)"
en:"Hit \3%s\1 %d time(s) (Damage %d)"
bp:"Acertou \3%s\1 %d vez(es) (Dano %d)"
cn:"命中 \3%s\1 %d 次 (造成伤害：%d)"

"You haven't hit anyone this round."
en:"You haven't hit anyone this round."
bp:"Você não acertou ninguém nesse round."
cn:"本轮没有击中任何人."

"Hit by \3%s\1 %d time(s) (Damage %d)"
en:"Hit by \3%s\1 %d time(s) (Damage %d)"
bp:"Atingido por \3%s\1 %d vez(es) (Dano %d)"
cn:"被击中 \3%s\1 %d 次 (造成伤害：%d)"

"You weren't hit this round."
en:"You weren't hit this round."
bp:"Você não foi atingido nesse round."
cn:"本轮没有被击中."

"(%d dmg / %d hits) to (%d dmg / %d hits) from \3%s\1 (%d HP)"
en:"(%d dmg / %d hits) to (%d dmg / %d hits) from \3%s\1 (%d HP)"
bp:"(%d dano / %d acertos) para (%d dano / %d acertos) de \3%s\1 (%d HP)"
cn:"(%d dmg / %d hits) to (%d dmg / %d hits) from \3%s\1 (%d HP)"

"No stats in this round."
en:"No stats in this round."
bp:"Nenhuma estatística nesse round."
cn:"本轮无统计数字."

"Match will start when all players join in game."
en:"Match will start when all players join in game."
bp:"A partida vai começar quando todos estiverem no jogo."
cn:"所有玩家进入游戏时比赛开始."

"All players are in teams and are ready!"
en:"All players are in teams and are ready!"
bp:"Todos os jogadores estão nos times e prontos!"
cn:"所有玩家加入队伍且已准备就绪!"

"WARMUP\n%d PLAYERS LEFT"
en:"WARMUP\n%d PLAYERS LEFT"
bp:"AQUECIMENTO\n%d JOGADORES RESTANTES"
cn:"有\n%d 名热身玩家"

"WARMUP\n%d PLAYER LEFT"
en:"WARMUP\n%d PLAYER LEFT"
bp:"AQUECIMENTO\n%d JOGADOR RESTANTE"
cn:"有\n%d 名热身玩家"

"STARTING MATCH"
en:"STARTING MATCH"
bp:"INICIANDO PARTIDA"
cn:"开始比赛"

"Vote Map:"
en:"Vote Map:"
bp:"Escolha do mapa:"
cn:"投票换图:"

"Starting Vote Map."
en:"Starting Vote Map."
bp:"Iniciando escolha do mapa."
cn:"开始投票换图."

"Changing map to \4%s\1..."
en:"Changing map to \4%s\1..."
bp:"Alterando mapa para \4%s\1..."
cn:"更换地图为：\4%s\1..."

"The map choice has failed: \3No votes."
en:"The map choice has failed: \3No votes."
bp:"A escolha do mapa falhou: \3Nenhum voto."
cn:"地图选择失败: \3没有投票."

"votes"
en:"votes"
bp:"votos"
cn:"投票"

"vote"
en:"vote"
bp:"voto"
cn:"投票"

"No votes..."
en:"No votes..."
bp:"Nenhum voto..."
cn:"没有投票..."

"Player Vote Menu:"
en:"Player Vote Menu:"
bp:"Menu de Votação:"
cn:"玩家投票菜单:"

"Vote for Kick"
en:"Vote for Kick"
bp:"Votar Kick"
cn:"投票踢人"

"Vote for Map"
en:"Vote for Map"
bp:"Votar Mapa"
cn:"换图投票"

"Vote for Tactical Timeout"
en:"Vote for Tactical Timeout"
bp:"Votar Pausa"
cn:"战术暂停投票"

"Vote for Restart Match"
en:"Vote for Restart Match"
bp:"Votar para reiniciar"
cn:"重启比赛投票"

"Vote Kick:"
en:"Vote Kick:"
bp:"Vote Kick:"
cn:"投票踢出:"

"We need \3%d\1 players in \3%s\1 team to Vote Kick."
en:"We need \3%d\1 players in \3%s\1 team to Vote Kick."
bp:"Preciamos de \3%d\1 jogadores no time \3%s\1 para o Vote Kick."
cn:"需要 \3%s\1 队伍中的 \3%d\1 名队员投票踢人."

"\3%s\1 voted to kick \3%s\1: %2.0f%% of votes to kick."
en:"\3%s\1 voted to kick \3%s\1: %2.0f%% of votes to kick."
bp:"\3%s\1 votou para kickar \3%s\1: %2.0f%% de votos para kickar."
cn:"\3%s\1 投票踢出 \3%s\1:需要获得 %2.0f%% 的同意票数方可踢出."

"Say \3.vote\1 to open vote kick."
en:"Say \3.vote\1 to open vote kick."
bp:"Say \3.vote\1 para abrir o vote kick."
cn:"Say \3.vote\1 开启投票踢人."

"Kicked by Vote Kick."
en:"Kicked by Vote Kick."
bp:"Kickado pelo Vote Kick."
cn:"被投票踢出服务器."

"\3%s\1 Kicked: \4%d\1 votes reached."
en:"\3%s\1 Kicked: \4%d\1 votes reached."
bp:"\3%s\1 Kickado: \4%d\1 votos alcançados."
cn:"\3%s\1 被踢出服务器: 获得\4%d\1 同意票."

"Already voted to kick: \3%s\1..."
en:"Already voted to kick: \3%s\1..."
bp:"Já votou para kickar: \3%s\1..."
cn:"已同意投票踢出: \3%s\1..."

"\3%s\1 nomitated \4%s\1: %2.0f%% of votes to change map."
en:"\3%s\1 nomitated \4%s\1: %2.0f%% of votes to change map."
bp:"\3%s\1 nomeou \4%s\1: %2.0f%% of votes to change map."
cn:"\3%s\1 提名换图：\4%s\1: 需要获得 %2.0f%% 的同意票数方可换图."

"Say \3.vote\1 to nominate a map."
en:"Say \3.vote\1 to nominate a map."
bp:"Say \3.vote\1 para nomear um mapa."
cn:"Say \3.vote\1 发起提名换图投票."

"Already nominated \3%s\1..."
en:"Already nominated \3%s\1..."
bp:"Já nomeou \3%s\1..."
cn:"已经获得提名 \3%s\1..."

"\3%s\1 from \3%s\1 voted for pause match: %2.0f%% of votes to pause match."
en:"\3%s\1 from \3%s\1 voted for pause match: %2.0f%% of votes to pause match."
bp:"\3%s\1 do time \3%s\1 votou para pausar a partida: %2.0f%% dos votos para pausar."
cn:"\3%s\1 来自 \3%s\1 支持暂停比赛: 需要获得 %2.0f%% 的同意票方可暂停比赛."

"Say \3.vote\1 to vote for a pause."
en:"Say \3.vote\1 to vote for a pause."
bp:"Say \3.vote\1 para votar uma pausa."
cn:"Say \3.vote\1 发起战术暂停投票."

"You already voted to pause the game."
en:"You already voted to pause the game."
bp:"Você já votou para pausar a partida."
cn:"你已投票赞成战术暂停."

"\3%s\1 voted to restart \3%s\1: %2.0f%% of votes to restart match."
en:"\3%s\1 voted to restart \3%s\1: %2.0f%% of votes to restart match."
bp:"\3%s\1 votou para reiniciar \3%s\1: %2.0f%% dos votos para reiniciar a partida."
cn:"\3%s\1 投票重新开始 \3%s\1: 需要获得 %2.0f%% 的同意票方可重新开始."

"Say \3.vote\1 to restart match."
en:"Say \3.vote\1 to restart match."
bp:"Say \3.vote\1 para reiniciar a partida."
cn:"Say \3.vote\1 发起重新开始比赛投票."

"Restarting match.."
en:"Restarting match.."
bp:"Reiniciando partida.."
cn:"重新开始比赛.."

"You already voted to retart match."
en:"You already voted to retart match."
bp:"Você já votou para reiniciar a partida."
cn:"你已投票同意重新开始比赛."

"Play Overtime"
en:"Play Overtime"
bp:"Jogar Overtime"
cn:"开始加时赛"

"Play sudden death round"
en:"Play sudden death round"
bp:"Jogar round de desempate"
cn:"开始进行突然死亡回合"

"End match with tied scores"
en:"End match with tied scores"
bp:"Finalizar partida com placar empatado"
cn:"平局结束比赛"

"Match is tied, what you want to do?"
en:"Match is tied, what you want to do?"
bp:"Placar empatado, o que você deseja fazer?"
cn:"比赛平局,下一步想做什么?"

"Match is tied, Overtime vote started."
en:"Match is tied, Overtime vote started."
bp:"Placar empatado, votação para jogar Overtime iniciada."
cn:"比赛平局, 开始进行加时赛投票."

"Match will continue in: \3Sudden Death Round."
en:"Match will continue in: \3Sudden Death Round."
bp:"A partida vai continar no: \3Round de morte súbita."
cn:"比赛继续: \3进行突然死亡回合."

"The choice of overtime failed: \3No votes."
en:"The choice of overtime failed: \3No votes."
bp:"A escolha do overtime falhou: \3Nenhum voto."
cn:"加时赛投票失败: \3没有选票."

"Overtime Vote:"
en:"Overtime Vote:"
bp:"Escolha do Overtime:"
cn:"加时赛投票:"

"Leaders Sorted"
en:"Leaders Sorted"
bp:"Capitães"
cn:"队长排序"

"Random"
en:"Random"
bp:"Automático"
cn:"随机"

"Not Sorted"
en:"Not Sorted"
bp:"Sem Sorteio"
cn:"未排序"

"Skill Sorted"
en:"Skill Sorted"
bp:"Balancear Skill"
cn:"技能排序"

"Game Mode:"
en:"Game Mode:"
bp:"Modo de Jogo:"
cn:"游戏模式:"

"Select teams started."
en:"Select teams started."
bp:"Escolha dos times iniciada."
cn:"开始选择队伍."

"The choice of the teams failed: \3No votes."
en:"The choice of the teams failed: \3No votes."
bp:"A escolha dos times falhou: \3Nenhum voto."
cn:"队伍选择失败: \3没有投票."

"Mixing teams now."
en:"Mixing teams now."
bp:"Misturando os times agora."
cn:"现在正在混合队伍."

"The teams will remain the same."
en:"The teams will remain the same."
bp:"Os times serão os mesmos."
cn:"队伍将保持不变."

"Balancing teams by skills."
en:"Balancing teams by skills."
bp:"Balanceando times por skill."
cn:"按照技能平衡队伍."

"Swaping teams now."
en:"Swaping teams now."
bp:"Trocando os times agora."
cn:"现在交换队伍."

"Deathmatch respawing is enabled until match begin!"
en:"Deathmatch respawing is enabled until match begin!"
bp:"Deathmatch habilitado até o início da partida!"
cn:"比赛开始前，启用死亡竞赛的重生功能!"

"Deathmatch respawing disabled."
en:"Deathmatch respawing disabled."
bp:"Deathmatch desabilitado."
cn:"禁用死亡竞赛的重生功能."

"%s won, what team you want?"
en:"%s won, what team you want?"
bp:"%s venceu, qual o time que você deseja?"
cn:"%s 获胜, 你想加入哪只队伍?"

"%s won Knife Round, swap teams vote started."
en:"%s won Knife Round, swap teams vote started."
bp:"%s venceu o Round Faca, escolha dos times iniciada."
cn:"%s 赢得拼刀局, 换边投票开始."

"Swap Teams Vote:"
en:"Swap Teams Vote:"
bp:"Escolha dos times:"
cn:"换边投票:"

**Comment by SmileYzn** [comment]
Fork matchbot, change things and do a pull request please.
If you do not know how to do that, upload you language.txt file to a hosting instead.

Is not safe copy and paste text from github page to a text file of project
