### ISSUE TITLE
HudMessage(Player->edict()) 

### ISSUE THREAD

**Issue by Gawnz1** [SmileYzn/MatchBot#44]
Sorry for the spam issue, but can't find another way to contact you for little help. Also I think this may be helpful to more people than me

I want to print a personal HudMessage to the client in Ready list function, but the server crash. How can I print it? Do I have to loop trough some players or?

https://github.com/SmileYzn/MatchBot/blob/main/MatchBot/MatchReady.cpp#L75
Like when I make new line with same code, but not with nullptr, but with Player->edict() it crash. On the normal SayText message it works.

Can you provide a little help. Thank you.

Sorry for the spam, but I gave up.. Tried my best to make it

**Comment by SmileYzn** [comment]
Sorry, this is not related with MatchBot. 

Also you can't send more than 4 hudmessages at once that already used to display player list.
