### ISSUE TITLE
[QUESTION/ISSUE?]mb_players_min & mb_players_max using readytimer for startgame

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#49]
Hi,

How suppose to work  mb_players_min and max? 

So if I have it like that  mb_players_min = 9 & mb_players_max =10

if I have 9 players the game starts but if i have 10 it wont start

[video](https://www.youtube.com/watch?v=mgchY3A9zbc)

**Comment by SmileYzn** [comment]
Players min is set to start the game, and players max is maximum of players in teams.

Is impossible that with 10 players game won't start, the logic is:

For ready system
```
if (PlayerCount[1] >= PlayersMin)
```

For timer system
```
auto NeededCount = (PlayersMin - gMatchUtil.GetPlayers(true, true).size());

if (NeededCount)
```

What is the logic to set needed players to 9 to start a game?
It will start unbalanced teams!!

Anyway if you still need thes, there is fixed
https://github.com/SmileYzn/MatchBot/actions/runs/4852019156

**Comment by yuyiken** [comment]
I thought it would be better do it with same variables thats why i asked. 
Anyways thank you. Anyways thank you.
