### ISSUE TITLE
not set gamename score!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#50]
![Screenshot (3)](https://user-images.githubusercontent.com/78939962/235438623-0060a42c-d944-4eb6-95cc-17f0e8e02e6f.png)

**Comment by noa1ms** [comment]
use linux?

**Comment by yuyiken** [comment]
Yes I have Debian 5.10.162-1, got same issue, its like i got score under this 2 characters ??.

**Comment by SmileYzn** [comment]
Edit it on language.txt!
