### ISSUE TITLE
halftime start player score issue!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#52]
halftime in 2nd halft player score are bug not icrease score player team score are ok plz fix it

**Comment by yuyiken** [comment]
Can confirm, in second half if u make kills in next startround they decrease.

**Comment by Escap3d** [comment]
> 
yes same problem :)

**Comment by noa1ms** [comment]
say .dmg  crash server

**Comment by yuyiken** [comment]
> say .dmg crash server

works fine for me with endstats round in 1 and 2.. please provide more information..

**Comment by Escap3d** [comment]
> 

Manualy cmd add in enable or disabled

**Comment by SmileYzn** [comment]
Trying to fix scoreboards on https://github.com/SmileYzn/MatchBot/actions/runs/4853775869
