### ISSUE TITLE
Suggestion:- match end show stats!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#58]
Can u add match end show stats player how much kills death etc…

**Comment by yuyiken** [comment]
It's really needed? You can check your score with scoreboard lol.

**Comment by Escap3d** [comment]
> It's really needed? You can check your score with scoreboard lol.

Some player ask me add this stats u will need then i will close it? 🙂

**Comment by SmileYzn** [comment]
It will done when is possible 👍
