### ISSUE TITLE
Suggestion: player disconnect server and player score..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#59]
Can u add one more code player playing the match then timwout for net disconnect and then reconnect the server when score was 0 .. can maintain scores kills and death player after reconnect the server..

Sorry my bad english..

**Comment by yuyiken** [comment]
I think this is more complex, because save only score? when player reconects he got money 800 + money when round ends.. if player had 10000k he lose it but if he has 0he win.. You dont know if the player will be more than 1 round disconnected... This is not automix logic, when if someone leaves another fill his spot..

**Comment by Escap3d** [comment]
> I think this is more complex, because save only score? when player reconects he got money 800 + money when round ends.. if player had 10000k he lose it but if he has 0he win.. You dont know if the player will be more than 1 round disconnected... This is not automix logic, when if someone leaves another fill his spot..

Maximum 3 rounds allowed to reconnect server to get back score kills death etc.. its a good for players to playing fun .. add veriable commands add if u dont need..

**Comment by SmileYzn** [comment]
Internal stats is saved even if a player leave game.
I will not restore anything if an player get disconnected. Is not only automix login, but is CS LOGIC!

**Comment by Escap3d** [comment]
> Internal stats is saved even if a player leave game.
> I will not restore anything if an player get disconnected. Is not only automix login, but is CS LOGIC!

Its a good idea.. its ok beo
