### ISSUE TITLE
Broken Menu Visualization

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#6]
Hi, 

I got this menu problems. 

Menu functionality works fine, 

But sometimes I got stuff like this. 

![20230322223811_1](https://user-images.githubusercontent.com/74840575/227044729-50119f5c-1eee-4fd9-a3a4-bb51fbcd08f9.jpg)

**Comment by SmileYzn** [comment]
Try to download latest GitHub action build, if still occurs i will check it.

Em qua., 22 de mar. de 2023 18:40, yuyiken ***@***.***>
escreveu:

**Comment by yuyiken** [comment]
Yes, it was from the last build actions. First I bulld from fork, thoght it was something i did, and happend to me in my windows bulld, then I tried your last linux actions on debian 10 and same problem. Sometimes it appears sometimes not. If you need more information let me know.

**Comment by SmileYzn** [comment]
It is lacking to reset some variable, i will look it
