### ISSUE TITLE
Suggestion:- ranking player system

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#60]
If possible to add ranking system??

**Comment by SmileYzn** [comment]
MatchBOT Generates match stats on stats folder automatically as .json files.

**Comment by Escap3d** [comment]
U add on ranking system in this mod?? :(

**Comment by SmileYzn** [comment]
> U add on ranking system in this mod?? :(

You need to find a way to organize ranking system, maybe i can create a new one to track these stats generated by matchbot.
