### ISSUE TITLE
!stop cmd server crash!!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#63]
plz fix it i can !stop cmd then voting start vote was complete and server crash...

**Comment by SmileYzn** [comment]
```
void CMatchBot::StopMatch(CBasePlayer* Player)
{
	// Check Accesss
	if (gMatchAdmin.Access(Player->entindex(), ADMIN_LEVEL_B))
	{
		// If match is running
		if (this->m_State >= STATE_FIRST_HALF && this->m_State <= STATE_OVERTIME)
...
```

Is impossible to use !stop command when vote is starting, please describe better where is vote

**Comment by Escap3d** [comment]
> ```
> void CMatchBot::StopMatch(CBasePlayer* Player)
> {
> 	// Check Accesss
> 	if (gMatchAdmin.Access(Player->entindex(), ADMIN_LEVEL_B))
> 	{
> 		// If match is running
> 		if (this->m_State >= STATE_FIRST_HALF && this->m_State <= STATE_OVERTIME)
> ...
> ```
> 
> 
>      
>   
> 
> Is impossible to use !stop command when vote is starting, please describe better where is vote

Bro after voting server crash

**Comment by SmileYzn** [comment]
@axl303

The projects are unrelated, i always test vote system with a single player (ME) alone in server and do not having any issues here. 

I can't predict a problem without a better description of what's going on.

Add-me on steam: https://steamcommunity.com/id/_SmileY/

**Comment by TrifonDinev** [comment]
> The projects are unrelated, i always test vote system with a single player (ME) alone in server and do not having any issues here.

I tested everything and I compared - Still the same thing. Just see the video and what I wrote you in DM at Discord.

**Comment by axl303** [comment]
> The projects are unrelated, i always test vote system with a single player (ME) alone in server and do not having any issues here.

Just see the information on Discord and the Video. Everything is described there step by step what I did. You won't catch the crash/freeze alone or just from 2-3-10 tries. See the video and your Discord DM

**Comment by Escap3d** [comment]
> > after voting server crash
> 
> I suppose the crash may be from something that I wrote in here: [SmileYzn/RePugMod#38](https://github.com/SmileYzn/RePugMod/issues/38) @SmileYzn , can you read your Discord?
> 
> Edit: @Escap3d, can you provide some info? Is it crash or freeze? What is going on, like if votes are not 5 - the server freeze or what? A video something?

Bro we arw playing a 5vs5 manualy match i dont use auto pug mod i am using only cmds and some players are leave the server then i !stop cmd use gor stop the match for deathmatch then auto voting start we voting select voting complete then vote for select any then sv cant not chnagw the map then sv crash not change the map thats happen here i dont have any video


Sorry for my bad english hope u understand

**Comment by axl303** [comment]
Here is the whole comment at what I did:
https://pastebin.com/raw/WtdB1MR1
The video is in discord I don't know how to share it.

> Bro we arw playing a 5vs5 manualy match i dont use auto pug mod i am using only cmds and some players are leave the server then i !stop cmd use gor stop the match for deathmatch then auto voting start we voting select voting complete then vote for select any then sv cant not chnagw the map then sv crash not change the map thats happen here i dont have any video

I assume this can be the same problem like mine? The vote timer finish and If not everyone voted - the server crash/freeze?
Does it crash or the server console is freezed?
