### ISSUE TITLE
Manual commands??

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#7]
Where is manual cmds for working on tournament competitive match server

**Comment by yuyiken** [comment]
Hello @Escap3d. 

What you mean with manual cmds for working. 

You want a CVAR List?

If you need All cvars, you can get it in matchbot.cfg or look for all "gMatchUtil.CvarRegister" in the project.

Or just manage game as admin in a server?

If you need to manage you have an admin menu typing !menu 

Then you can go to point 6 (Control Match)

And there you can start stop pause restart...

**Comment by Escap3d** [comment]
U r right bro i just want to use for peronal tournaments is this mod .. i want to use in manual admin use u say use it !menu
Knife round
Side voting 
Half round 15 after swtching
15/15 overtime 
Its controling admin not mod. Not controling mod


Sorry mu bad english hope u understand

**Comment by yuyiken** [comment]
@Escap3d I suggest you to read all cvars in matchbot.cfg and project. They all are commented to explain the functionality.
This mod is still in development and constantly can change adding or removing cvars. 
Pay attention to all new cvars that can be added or removed. Maybe you can find new on that can be good for your server.

**Comment by Escap3d** [comment]
Plzz share latest if u have new fixing linux metamod plugin

**Comment by SmileYzn** [comment]
Download it here:

https://github.com/SmileYzn/MatchBot/actions/runs/4507782252

Ps. Just paste contents on cstrike folder, or just pick up the wanted files. I also recommend you to always copy and reconfigure matchbot.cfg, since as @yuyiken said, i can add a new cvars or change file content bettwen updates.

**Comment by Escap3d** [comment]
small tiny help ur if u dont mind plzz edit for me limux only 
![Screenshot 2023-03-24 205736](https://user-images.githubusercontent.com/78939962/227577669-977beb04-463b-435f-bbeb-5e35da204b3e.png)

**Comment by SmileYzn** [comment]
Did you still need to remove credits?
Please, do not ask something else here.... Do yourself..

**Comment by Escap3d** [comment]
> Did you still need to remove credits? Please, do not ask something else here.... Do yourself..
how to compile os windows 11 to compile linux file i have c++ i can compile dll file not .so
