### ISSUE TITLE
server crash new action build!!!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#71]
server crash after !start for cmd

**Comment by Escap3d** [comment]
plz fix it ita new report not old :(

**Comment by SmileYzn** [comment]
Again i did not have an crystal ball.
Did you even tryed to put -debug on hlds startup line to generate debug.log if crash?

No? I can't guess bugs without that info!

I created the issue templates for that and will ignore it if these information is not send on bug report.

**Comment by Escap3d** [comment]
[debug.log](https://github.com/SmileYzn/MatchBot/files/11779864/debug.log)
