### ISSUE TITLE
server crash report!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#72]
----------------------------------------------
CRASH: Mon Jun 19 05:19:39 UTC 2023
Start Line: ./hlds_linux -game cstrike -pidfile ogp_game_startup.pid +map de_dust2 +ip 172.31.3.86 +port 27015 +maxplayers 18 -insecure -tickrate 100 +pingboost 2 -debug +sys_ticrate 1000
End of crash report
----------------------------------------------

**Comment by Escap3d** [comment]
Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
dlopen failed trying to load:
/home/gamehome1/.steam/sdk32/steamclient.so
with error:
/home/gamehome1/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 17:33:11 Aug 24 2022 (3056)
STEAM Auth Server
Server IP address 172.31.3.86:27015
   
   Metamod version 1.21-am  Copyright (c) 2001-2013 Will Day <willday@metamod.org>
   Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.
   
[ReAuthCheck] Version: 0.1.6 Linux 'Counter-Strike 1.6'
[ReAuthCheck] Success: Configuration executed.
[ReAuthCheck] Success: Build ReHLDS version defined Linux '3056'

   AMX Mod X version 1.9.0.5271 Copyright (c) 2004-2015 AMX Mod X Development Team 
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under 
   certain conditions; type 'amxx gpl' for details.
  
[WHB] Version: 1.5.697 Linux (Usage SSE 4.1)
[WHB] Success: Build ReHLDS version defined Linux '3056'
[WHB] Success: Configuration executed.
[ReSRDetector] Version: 0.1.0 Linux 'Counter-Strike 1.6'
[ReSRDetector] Success: Configuration executed.
[ReSRDetector] Success: Build ReHLDS version defined Linux '3056'
[BOT] ReHLDS API minor version mismatch; expected at least 13, real 11
[BOT] Please update the ReHLDS up to a minor version API >= 13
ReGameDLL version: 5.21.0.556-dev
L 06/20/2023 - 04:35:42: -------- Mapchange to de_dust2 --------
[ReAimDetector] Version: 0.2.2 Linux 'Counter-Strike 1.6'
[ReAimDetector] Success: Build ReHLDS version defined Linux '3056'.
Executing ReGameDLL Configuration File 
[AMXX] Loaded 18 admins from file
L 06/20/2023 - 04:35:43: [AMXX] Failed to open dictionary file: cstrike/addons/amxmodx/data/lang/PWRemover.txt
Executing AMX Mod X Configuration File 
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
/home/gamehome1/.steam/sdk32/steamclient.so
with error:
/home/gamehome1/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit

Connection to Steam servers successful.
   VAC secure mode disabled.
Rcon from 172.31.3.86:33898:
rcon 1054658069 "bugify007" quit
Tue Jun 20 04:41:51 UTC 2023: Server Quit
Server './hlds_run -game cstrike -pidfile ogp_game_startup.pid +map de_dust2 +ip 172.31.3.86 +port 27015 +maxplayers 18 -insecure -tickrate 100 +pingboost 2 -debug +sys_ticrate 1000' crashed with exit code 0.  Respawning...
Enabling debug mode
./hlds_run: 1: gdb: not found
Please install gdb first.
goto http://www.gnu.org/software/gdb/ 
Auto-restarting the server on crash

**Comment by noa1ms** [comment]
Apt install gdb or yum install gdb

**Comment by SmileYzn** [comment]
"rcon 1054658069 "bugify007" quit"

Bug?

**Comment by Escap3d** [comment]
> "rcon [1054658069](tel:1054658069) "bugify007" quit"
> 
> Bug?

Sorry its server rcon😅
