### ISSUE TITLE
Server crash!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#75]
- meta list
 - Currently loaded plugins:
      description      stat pend  file                        vers         src  load  unload
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.so          v1.9.0.5294  ini  Start ANY  
 [ 2] SafeNameAndChat  RUN   -    SafeNameAndChat.so          v1.1         ini  ANY   ANY  
 [ 3] Reunion          RUN   -    reunion_mm_i386.so          v0.1.0.137   ini  Start Never
 [ 4] ReAuthCheck      RUN   -    reauthcheck_mm_i386.so      v0.1.6       ini  Start Never
 [ 5] VoiceTranscoder  RUN   -    VoiceTranscoder.so          v2017RC5     ini  ANY   ANY  
 [ 6] WHBlocker        RUN   -    whblocker_mm_i386.so        v1.5.697     ini  Chlvl ANY  
 [ 7] Rechecker        RUN   -    rechecker_mm_i386.so        v2.7         ini  Chlvl ANY  
 [ 8] ReSRDetector     RUN   -    resrdetector_mm_i386.so     v0.1.0       ini  Chlvl ANY  
 [ 9] HitBox Fix       RUN   -    hitbox_fix_mm_i386.so       v1.1.2       ini  Start ANY  
 [10] Match Bot        RUN   -    matchbot_mm.so              v0.0.2       ini  ANY   ANY  
 [11] CStrike          RUN   -    cstrike_amxx_i386.so        v1.9.0.5294  pl1  ANY   ANY  
 [12] CSX              RUN   -    csx_amxx_i386.so            v1.9.0.5294  pl1  ANY   ANY  
 [13] ReAimDetector    RUN   -    reaimdetector_amxx_i386.so  v0.2.2       pl1  ANY   Never
13 plugins, 13 running
 - amxx plugins
 - Currently loaded plugins:
       name                    version     author            file             status   
 [  1] Admin Base              1.9.0.5294  AMXX Dev Team     admin.amxx       running  
 [  2] Admin Commands          1.9.0.5294  AMXX Dev Team     admincmd.amxx    running  
 [  3] Admin Help              1.9.0.5294  AMXX Dev Team     adminhelp.amxx   running  
 [  4] Slots Reservation       1.9.0.5294  AMXX Dev Team     adminslots.amxx  running  
 [  5] Multi-Lingual System    1.9.0.5294  AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.9.0.5294  AMXX Dev Team     menufront.amxx   running  
 [  7] Commands Menu           1.9.0.5294  AMXX Dev Team     cmdmenu.amxx     running  
 [  8] Players Menu            1.9.0.5294  AMXX Dev Team     plmenu.amxx      running  
 [  9] Maps Menu               1.9.0.5294  AMXX Dev Team     mapsmenu.amxx    running  
 [ 10] Plugin Menu             1.9.0.5294  AMXX Dev Team     pluginmenu.amxx  running  
 [ 11] Admin Chat              1.9.0.5294  AMXX Dev Team     adminchat.amxx   running  
 [ 12] Anti Flood              1.9.0.5294  AMXX Dev Team     antiflood.amxx   running  
 [ 13] Admin Votes             1.9.0.5294  AMXX Dev Team     adminvote.amxx   running  
X[ 14] Pause Plugins           1.9.0.5294  AMXX Dev Team     pausecfg.amxx    running   [ 15] Stats Configuration     1.9.0.5294  AMXX Dev Team     statscfg.amxx    running  
 [ 16] Restrict Weapons        1.9.0.5294  AMXX Dev Team     restmenu.amxx    running  
 [ 17] CS Misc. Stats          1.9.0.5294  AMXX Dev Team     miscstats.amxx   running  
 [ 18] CS Stats Logging        1.9.0.5294  AMXX Dev Team     stats_logging.a  running  
 [ 19] ReAimDetector API       0.2.2       ReHLDS Team       reaimdetector.a  running  
 [ 20] PW Remover              2.0         Escape*           PWRemover.amxx   running  
20 plugins, 20 running

 - amxx version
 - AMX Mod X 1.9.0.5294 (http://www.amxmodx.org)
Authors:
	David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
	Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
	Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
	Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Dec  3 2021 15:54:56
Built from: https://github.com/alliedmodders/amxmodx/commit/363871a
Build ID: 5294:363871a
Core mode: JIT+ASM32

**Server Details (please complete the following information):**
 - Slots 18
 - Tested with bots? :- not
 - Other informations

CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.
Sun Jun 25 14:59:28 UTC 2023: Server Quit
Server './hlds_run -game cstrike -pidfile ogp_game_startup.pid +map de_dust2 +ip 172.31.3.86 +port 27015 +maxplayers 18 -insecure -tickrate 100 +pingboost 2 -debug -gdb -debuglog +sys_ticrate 1000' crashed with exit code 0.  Respawning...
Enabling debug mode
./hlds_run: 1: -debuglog: not found
Please install gdb first.
goto http://www.gnu.org/software/gdb/

**Comment by axl303** [comment]
Bro, no need to spam crash issues!! Just open one and provide/try to provide information or see if there are already open issues like yours.

Also install GDB
./hlds_run: 1: -debuglog: not found
Please install gdb first.
Noa1ms told you in the previous issue how to - > https://github.com/SmileYzn/MatchBot/issues/72#issuecomment-1598398823

**Comment by Escap3d** [comment]
> Bro, no need to spam crash issues!! Just open one and provide/try to provide information or see if there are already open issues like yours.
> 
> Also install GDB ./hlds_run: 1: -debuglog: not found Please install gdb first. Noa1ms told you in the previous issue how to - > [#72 (comment)](https://github.com/SmileYzn/MatchBot/issues/72#issuecomment-1598398823)

We are disabled its mod can not run this mod because sv crashing problem i !start to run start match then sv was crash

**Comment by SmileYzn** [comment]
> > Bro, no need to spam crash issues!! Just open one and provide/try to provide information or see if there are already open issues like yours.
> > Also install GDB ./hlds_run: 1: -debuglog: not found Please install gdb first. Noa1ms told you in the previous issue how to - > [#72 (comment)](https://github.com/SmileYzn/MatchBot/issues/72#issuecomment-1598398823)
> 
> We are disabled its mod can not run this mod because sv crashing problem i !start to run start match then sv was crash

Did you tried to install gdb?

If you still thinking that i am ignoring issues?
I'm a free time coder, if you need a special support only for you issues. You know what you need to do!

I'm also trying to find the reason of crash! I do not have a crystal ball!

Since this issue appears about crashes, i'm trying to debug the mod and find where is the problem.
Do not blame if you can't install gdb in your machine for any reason, is totally out of scope of this project!
