### ISSUE TITLE
Ready/Not Ready player list suggestion

### ISSUE THREAD

**Issue by drakin001** [SmileYzn/MatchBot#77]
Hello!

maybe add a command to turn on/turn off ready and not ready player list on the screen bacause alot of players play on 640x480 resolution, so when players join and  we wait for last 1 or 2 players,  ready player list takes up half the screen

**Comment by SmileYzn** [comment]
Did you can post an screenshot?
I can create other ready list type only with player count in screen

**Comment by vegas003** [comment]
player count also helps but a command to turn off would be better
like mb_show_ready_list 0 ?

i have seen it in some plugins or maybe i am asking too much i don't know

**Comment by SmileYzn** [comment]
@vegas003 No worry bro, You are sure!

I mean, ready list is big on 640 resolution.
I can do some text in center or other position like:

"WARMUP\n%d PLAYERS LEFT TO BE READY"

**Comment by vegas003** [comment]
not ready list can be below radar and players ready is a number like this screenshot
![20230707185542_1](https://github.com/SmileYzn/MatchBot/assets/23008063/baeae520-ed11-497b-9016-450721127171)

**Comment by SmileYzn** [comment]
On the left side below the radar:

Not Ready:
SmileYzn 
vegas003
yuyiken 
Player

6 Players ready. Say .ready.

?>

**Comment by vegas003** [comment]
> 

yes
type .ready rather then say .ready

**Comment by axl303** [comment]
> player count also helps but a command to turn off would be better like mb_show_ready_list 0 ?
> 
The cvar is a good suggestion. 

Another suggestion is to add mb_ready_hudmessage_mode 1/2
With 1 to be as it is now. 
With 2 to be more minimalistic like: Warmup\nReady 0 of 10\nNot ready players 0/10\nSay .ready

This is just a idea.

**Comment by vegas003** [comment]
you can close this if you don't like the idea its ok

**Comment by SmileYzn** [comment]
@vegas003 
I still fixing bugs on matchbot, can't work on this for now!

**Comment by SmileYzn** [comment]
There is:

Linux: https://github.com/SmileYzn/MatchBot/actions/runs/7766685770
Windows: https://github.com/SmileYzn/MatchBot/actions/runs/7766685769

Ps.
![image](https://github.com/SmileYzn/MatchBot/assets/5851851/aa341792-cf58-430a-9a7b-0c02e07e4427)
