### ISSUE TITLE
Issue: Cant buy when game is paused from 0:45 to end pause period.

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#82]
**Describe the bug**
Cant buy on 1 min pause time from 0:45 to end pause. 
When starts freezetime after pause time of round I can buy again. 

**To Reproduce**

1ºReproduce a pause in live game. 
2º Try to buy from beetwen 1:00 - 0:45. You can. 
3º From 0:44-Finish Pause Time you cant. 
4º When starts freezetime after pause finished you can buy again. 

If you dont understand me I can make video.

**Comment by SmileYzn** [comment]
That is because of mp_buytime variable that is being reset after pause end!

**Comment by SmileYzn** [comment]
Test new fix here: https://github.com/SmileYzn/MatchBot/actions/runs/5564065695

**Comment by yuyiken** [comment]
I'l try it today.

**Comment by yuyiken** [comment]
@SmileYzn not work for me bro.

**Comment by yuyiken** [comment]
@SmileYzn 
Fixed it here: https://github.com/SmileYzn/MatchBot/pull/88
