### ISSUE TITLE
matchbot json file error!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#83]
![Screenshot 2023-07-16 163848](https://github.com/SmileYzn/MatchBot/assets/78939962/3c73c3a7-43fe-417f-bdef-f446f9dc51a5)

Error in windows rehlds console file name json error....

**Comment by SmileYzn** [comment]
Did you can post original json file?

**Comment by Escap3d** [comment]
> Did you can post original json file?

language.json
user.json
maps.json
can not b work properly

**Comment by SmileYzn** [comment]
I will ask again, did you can post the content of each file on pastebin.com and post links here?

I have sure that is malformed duo bad editing.

**Comment by Escap3d** [comment]
> I will ask again, did you can post the content of each file on pastebin.com and post links here?
> 
> I have sure that is malformed duo bad editing.

which file ?

**Comment by SmileYzn** [comment]
all of json files

**Comment by Escap3d** [comment]
https://pastebin.com/kSUPjg39

**Comment by rilletcs** [comment]
> https://pastebin.com/kSUPjg39
> 
> https://pastebin.com/nnSrq3Bg
> 
> https://pastebin.com/CREFSv52

Hey, the json format has rules, you are not following any of these rules, it is obvious that the library will not be able to do the parser.
[https://jsonformatter.org/json-parser](https://jsonformatter.org/json-parser)
![image](https://github.com/SmileYzn/MatchBot/assets/92688145/36b95984-8df8-4734-9fa1-e6da821b248a)

Try to look at how json format works:
[https://codebeautify.org/blog/how-to-create-json-file/](https://codebeautify.org/blog/how-to-create-json-file/)

Comments are not part of the [json specification](https://datatracker.ietf.org/doc/html/rfc8259), it is a feature that the nlohmann library supports.

You can't just drop the text in there and expect it to work, the json format has rules for arrays, objects, etc....
```json
[
	{
		"Name": "Player",
		"Auth": "STEAM_ID_LAN",
		"Flags": "abcdefghijklmnopqrstuvy"
	},
	{
		"Name": "Escape*",
		"Auth": "STEAM_0:1:482576517",
		"Flags": "abcdefghijklmnopqrstuvy"
	},
	{
		"Name": "hrs",
		"Auth": "STEAM_0:0:523974831",
		"Flags": "abcdefghijklmnopqrstuvy"
	}
]
```
![image](https://github.com/SmileYzn/MatchBot/assets/92688145/5340bd77-556f-4f2e-a9fc-9ddb45e2fea0)

**Comment by Escap3d** [comment]
> > https://pastebin.com/kSUPjg39
> > https://pastebin.com/nnSrq3Bg
> > https://pastebin.com/CREFSv52
> 
> Hey, the json format has rules, you are not following any of these rules, it is obvious that the library will not be able to do the parser. https://jsonformatter.org/json-parser ![image](https://user-images.githubusercontent.com/92688145/255352118-36b95984-8df8-4734-9fa1-e6da821b248a.png)
> 
> Try to look at how json format works: https://codebeautify.org/blog/how-to-create-json-file/
> 
> Comments are not part of the [json specification](https://datatracker.ietf.org/doc/html/rfc8259), it is a feature that the nlohmann library supports.
> 
> You can't just drop the text in there and expect it to work, the json format has rules for arrays, objects, etc....
> 
> ```json
> [
> 	{
> 		"Name": "Player",
> 		"Auth": "STEAM_ID_LAN",
> 		"Flags": "abcdefghijklmnopqrstuvy"
> 	},
> 	{
> 		"Name": "Escape*",
> 		"Auth": "STEAM_0:1:482576517",
> 		"Flags": "abcdefghijklmnopqrstuvy"
> 	},
> 	{
> 		"Name": "hrs",
> 		"Auth": "STEAM_0:0:523974831",
> 		"Flags": "abcdefghijklmnopqrstuvy"
> 	}
> ]
> ```
> 
> ![image](https://user-images.githubusercontent.com/92688145/255352078-5340bd77-556f-4f2e-a9fc-9ddb45e2fea0.png)

But adminship not working i am follow all stp…

**Comment by Escap3d** [comment]
@SmileYzn bro fix it plzz

**Comment by rilletcs** [comment]
> @SmileYzn bro fix it plzz

Saying that it is not working does not help at all, the map file has a , (comma) in the last item indicating that there should be one more entry, but there is no... This means that an exception will be thrown because the json structure is incorrect...
![image](https://github.com/SmileYzn/MatchBot/assets/92688145/99de6a2a-c2ec-4284-9490-e4e65be78738)

Use https://jsonformatter.org/json-parser to know if your file is completely correct (remove comments in the file if there are any).
```json
[
	"de_dust2",
	"de_tuscan",
	"de_nuke",
	"de_inferno",
	"de_mirage",
	"de_train", <---------------
]
```
Read my previous comment, you must respect the structure of the json file or it will not work.

@SmileYzn This problem is not related to MatchBot but to JSON Syntax and maybe should be closed.

**Comment by Escap3d** [comment]
> ```json
> <---------------
> ```

I AM SAYING ADMIN SHIP MATCHBOT NOT WORKING I AM CAN NOT ACCESS ANY COMMANDS LIKE THAT !START !STOP !CONTROL NOT WORKING MOD ONLY WORK ON AMXMODX ADMINSHIP

**Comment by SmileYzn** [comment]
<details>
  <summary>SEE THE SCREENSHOT</summary>
  
  ![image](https://github.com/SmileYzn/MatchBot/assets/5851851/adedb67e-e407-4ed2-9ccf-4af2ab71fae0)
</details>

No errors with admin system even using a commented JSON!
Make sure that is not related with new translation and command prefix for admins!

**Comment by Escap3d** [comment]
> SEE THE SCREENSHOT
> No errors with admin system even using a commented JSON! Make sure that is not related with new translation and command prefix for admins!

![E5A4CE6C-906C-4226-A26E-EBDFFB1CCC8F](https://github.com/SmileYzn/MatchBot/assets/78939962/7f956bf0-4b4c-44d8-9b1a-50b2c1f0df6b)

**Comment by SmileYzn** [comment]
mb_menu not work?

**Comment by rilletcs** [comment]
> > ```json
> > <---------------
> > ```
> 
> I AM SAYING ADMIN SHIP MATCHBOT NOT WORKING I AM CAN NOT ACCESS ANY COMMANDS LIKE THAT !START !STOP !CONTROL NOT WORKING MOD ONLY WORK ON AMXMODX ADMINSHIP
> 
> https://www.mediafire.com/file/sdk52r811mn97c9/2023-07-24+21-26-41.mp4/file
> 
> look this video @SmileYzn @rilletcs

I watched your video, and your users.json file is still wrong.
![image](https://github.com/SmileYzn/MatchBot/assets/92688145/bff6c4fb-1167-4b73-a9ab-089d862ba4b4)

The syntax in your file:
```json
[
	{
		Name: Escape*
		Auth: "STEAM_0:1:482576517
		Flags: "abcdefghijklmnopqrstuvy
	}
]
```
As it should be:
```json
[
	{
		"Name": "Escape*",
		"Auth": "STEAM_0:1:482576517",
		"Flags": "abcdefghijklmnopqrstuvy"
	}
]
```

The github markdown is showing you the error and you ignore it, and every time I mention that you are not following the rules that the json format uses you say that everything is correct and nothing works.

**Comment by Escap3d** [comment]
> > > ```json
> > > <---------------
> > > ```
> > 
> > 
> > I AM SAYING ADMIN SHIP MATCHBOT NOT WORKING I AM CAN NOT ACCESS ANY COMMANDS LIKE THAT !START !STOP !CONTROL NOT WORKING MOD ONLY WORK ON AMXMODX ADMINSHIP
> > https://www.mediafire.com/file/sdk52r811mn97c9/2023-07-24+21-26-41.mp4/file
> > look this video @SmileYzn @rilletcs
> 
> I watched your video, and your users.json file is still wrong. ![image](https://user-images.githubusercontent.com/92688145/255710370-bff6c4fb-1167-4b73-a9ab-089d862ba4b4.png)
> 
> The syntax in your file:
> 
> ```json
> [
> 	{
> 		Name: Escape*
> 		Auth: STEAM_0:1:482576517
> 		Flags: "abcdefghijklmnopqrstuvy
> 	}
> ]
> ```
> 
> As it should be:
> 
> ```json
> [
> 	{
> 		"Name": "Escape*",
> 		"Auth": "STEAM_0:1:482576517",
> 		"Flags": "abcdefghijklmnopqrstuvy"
> 	}
> ]
> ```
> 
> The github markdown is showing you the error and you ignore it, and every time I mention that you are not following the rules that the json format uses you say that everything is correct and nothing works.

https://www.mediafire.com/file/cwglrxqyw3usddk/2023-07-25+19-43-45.mp4/file


not work

**Comment by SmileYzn** [comment]
@Escap3d 
The MatchBot is not running on video!

If an player (Admin or not) say with prefixes . or !, that !start command will never appear on chat. You problem is not related with users.json

**Comment by Escap3d** [comment]
> @Escap3d The MatchBot is not running on video! Where is the hudmessages or chat message when you enter in server? Even in server console matchbot do not display any messages.
> 
> If an player (Admin or not) say with prefixes . or !, that !start command will never appear on chat. You problem is not related with users.json
> 
> Please, pay attention of all things in server

i am already in server bro

**Comment by yuyiken** [comment]
Hello, I saw this issue with !commands. 

I was testing last build and got this issue too. 

But my file is well, so I tested console commands instead and works from console but ! commands not. 

https://www.youtube.com/watch?v=7qjjXAF1NWA

**Comment by vegas003** [comment]
hello, 

yes @yuyiken is right, admin commands are not working with ! prefix in chat @SmileYzn

**Comment by yuyiken** [comment]
@drakin001 actually it is matchbot.cfg issue because is overwriting mb_admin_prefix from "!" to this "." thats why you put !commands not works on chat. I'm trying to fix. Deleting second mb_admin_prefix "." should solve the issue. But it needs to be fixed anyways.
