### ISSUE TITLE
Building and ISO C++

### ISSUE THREAD

**Issue by rilletcs** [SmileYzn/MatchBot#84]
The current project compiles without any problem on **Windows** using the configuration:
> Visual Studio 2022
> ISO C++17 Standard
> Platform Toolset v143

My suggestion is to migrate to the **C++17**. This would allow to use _std::string_view, inline, std::filesystem, if constexpr, structured bindings, initializers if and switch, fold expressions, attributes_...

Ref: [https://en.cppreference.com/w/cpp/17](https://en.cppreference.com/w/cpp/17)

Since moving to **C++17** won't create problems, but allows using more cross-platform features, is there any special reason to stay in **C++11**/**C++14**?

Since there are no instructions for the compilation of the project, it might be ideal to start thinking about the requirements for the compilation and the minimum OS version. The project on Ubuntu 20.04 was broken until your commit 3 days ago adjusted the makefile and reverted from gcc-5 to gcc-4.8.

**Comment by SmileYzn** [comment]
I will only stay on c++11 because of Linux builds.

**Comment by Wolf3s** [comment]
> I will only stay on c++11 because of Linux builds.

You could support C++ 17

**Comment by SmileYzn** [comment]
> > I will only stay on c++11 because of Linux builds.
> 
> You could support C++ 17

Yes, but HLDS only support till c++11 and i did not have an idea how make it fully commpatible with c++17

**Comment by lucianene** [comment]
People should start throwing PR's instead of complaining :D ...

**Comment by SmileYzn** [comment]
> People should start throwing PR's instead of complaining :D ... I'll research myself if it's possible and maybe get back if I get it working.

If you research, you will see some people using cmake hehehehe and some things to get this done.
To be honest, valve fucked HLDS a lot since is still using C+11. And it is a outdated software, nothing that we can do is still in C++11 for now!

**Comment by SmileYzn** [comment]
> > People should start throwing PR's instead of complaining :D ... I'll research myself if it's possible and maybe get back if I get it working.
> 
> If you research, you will see some people using cmake hehehehe and some things to get this done. To be honest, valve fucked HLDS a lot since is still using C+11. And it is a outdated software, nothing that we can do is still in C++11 for now!

Finally this is changing, i just can not setup a latest HLDS aniversary update with Re-HLDS, that do not work, i think valve changed some things in HLDS.

Let's test to see if C++ 17 can be supported in a future.

Thanks

@rilletcs 
@lucianene 
@Wolf3s 

I really appreciate all the ideas 🙏

**Comment by Wolf3s** [comment]
> > > People should start throwing PR's instead of complaining :D ... I'll research myself if it's possible and maybe get back if I get it working.
> > 
> > 
> > If you research, you will see some people using cmake hehehehe and some things to get this done. To be honest, valve fucked HLDS a lot since is still using C+11. And it is a outdated software, nothing that we can do is still in C++11 for now!
> 
> Finally this is changing, i just can not setup a latest HLDS aniversary update with Re-HLDS, that do not work, i think valve changed some things in HLDS.
> 
> Let's test to see if C++ 17 can be supported in a future.
> 
> Thanks
> 
> @rilletcs @lucianene @Wolf3s
> 
> I really appreciate all the ideas 🙏

No problem.

**Comment by SmileYzn** [comment]
Migrated to C++14.
Let's fuck all things :D
