### ISSUE TITLE
C4 Bug Spawn.

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#89]
Hi @SmileYzn 

Few days ago I got this bug. 

First of all I don't know if its matchbot bug or regamedll. 

I wasn't on server but I got demo from the guy. 

Description of bug:

On first round after LO3 Restarts C4 don't spawn, but on second round 2 players get a C4. 

What happened. If you watch video. After 2 first restart of LO3 Terrorist player got C4 but on last one when game started. 

Terrorist dont get C4. So round was played as normal but without C4. 

Second round if you check on video 1:06 Player called :C dont have any C4.

He is the one who drop all weapons on 1:15 and by magic he drop c4. You can check that on radar he hasnt c4 until he pick up it after drop or scoreboard.

Additions: This version of matchbot is last from release, I added few texts, and demo recorder. 

```
      description      stat pend  file                   vers      src  load  unload
 [ 1] SafeNameAndChat  RUN   -    SafeNameAndChat.so     v1.1      ini  ANY   ANY  
 [ 2] VoiceTranscoder  RUN   -    VoiceTranscoder.so     v2017RC5  ini  ANY   ANY  
 [ 3] WHBlocker        RUN   -    whblocker_mm_i386.so   v1.5.697  ini  Chlvl ANY  
 [ 4] Rechecker        RUN   -    rechecker_mm_i386.so   v2.5      ini  Chlvl ANY  
 [ 5] HitBox Fix       RUN   -    hitbox_fix_mm_i386.so  v1.1.2    ini  Start ANY  
 [ 6] Match Bot        RUN   -    matchbot_mm.so         v1.0.0    ini  ANY   ANY  
```

https://www.youtube.com/watch?v=uRTZFCCjPJ4

**Comment by drk1351** [comment]
complete the start.cfg with the commands in esl, otherwise it works from halftime and that's why it takes C4 because there is no use of C4 during the knife round, Smiley, could you solve the knife round so that even if no one wins, it ends for the knife round, and when the sharp starts, there should be preparation time so that there can be a discussion between the teams, it would be great 10/10

**Comment by yuyiken** [comment]
@drk1351 Hello, thank you for your reply, just take in mind when It gets LO3 Restarts first two restarts player has C4 but after third one C4 dissapeared and appeared on player on next round. I don't think that this is relationated with start.cfg.

**Comment by drk1351** [comment]
This is guns good? // Block Shieldgun, HE, C4, Smokegrenade, Flashbang and Defuser
mb_restrict_weapons 		"100010100100000000000000010000001000000

**Comment by yuyiken** [comment]
> 
This weapons are blocked in warmup, but in game are unlocked since all cvars change before LO3 run, and on video you can appreciate bomb spawn on 2 rr

**Comment by SmileYzn** [comment]
I will create a lo3.cfg, so restarts can be done more naturally than forcing using task system!

**Comment by SmileYzn** [comment]
Please open other issue with json file content that is throwing that exeption

**Comment by drk1351** [comment]
now good im stuck, ty for your time !

**Comment by drk1351** [comment]
it just doesn't have access to this command for some reason. no admin :c
