### ISSUE TITLE
pause freezetime not working..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/MatchBot#9]
pause freeztime not working only work on match cfg then freeztime show but not pause time freez and some time map change server crash aftar map change... plzz fiz it

And 1 more suggestion add manual !knife round for team side selection

**Comment by SmileYzn** [comment]
Did you downloaded latest action build? I doubt. 
The restart map crash already been fixed a lot versions ago.

About manual knife round, just set mb_knife_round cvar to 1 before start match, or just change it to 0 to disable it.

Did you can make a video to see what is happen whit freezetime?

**Comment by Escap3d** [comment]
My friend told me that when switched in round 15, restart was not happening and startmoney was also not increasing.Freezetime also did not happen when the match was frozen and restarted, but the freezetime was showing but the timer was showing up.

**Comment by Escap3d** [comment]
] amx_cvar mb_knife_round 1
[AMXX] You have no access to that cvar
] amx_cvar mb_knife_round 0
[AMXX] You have no access to that cvar
[TORNI S16] Starting Vote Map.
[TORNI S16] Escape* /A/ choosed de_tuscan
[TORNI S16] Changing map to de_tuscan...
server was crash i was using cmd control then votemap map change and server was crash :(

**Comment by Escap3d** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/78939962/228012771-8976729b-d669-4637-bd25-ece77715bf3b.png)
![Screenshot (12)](https://user-images.githubusercontent.com/78939962/228012780-72514f4c-0a22-4211-8f6e-d3b9f8af40b3.png)

**Comment by SmileYzn** [comment]
Post output of these commands here:

version
game version
meta list
meta version
meta info Match Bot

Ps. Admins shoud be added in matchbot too, not onlyt on amxmodx

**Comment by Escap3d** [comment]
![Screenshot 2023-03-27 230451](https://user-images.githubusercontent.com/78939962/228028679-88077bf4-8eea-494e-ba9f-72a646d146e6.png)
![Screenshot 2023-03-27 230509](https://user-images.githubusercontent.com/78939962/228028688-f5348ade-ed85-4b88-8341-1abe17258b8a.png)
![Screenshot 2023-03-27 230540](https://user-images.githubusercontent.com/78939962/228028693-1a5be321-5d01-4162-bb1b-6f192c287f48.png)
![Screenshot 2023-03-27 230730](https://user-images.githubusercontent.com/78939962/228028696-5249a6e8-0bfa-4162-837a-daa7a9131b61.png)

**Comment by SmileYzn** [comment]
Dear god, post inside code tag in next time. not only images.

Did you can use administrator commands from match bot inside server?
The admin.ini is completely wrong, is not just a copy and paste of amxx admins.

And you have a lot other metamod plugins and an complete amxmodx install in server. Did you can test wtihout all of those plugins only matchbot?

I can´t support any plugin outside matchbot.

**Comment by Escap3d** [comment]
you mean to say that in user.ini admin make amxmodx then working fine?

**Comment by Escap3d** [comment]
!votemap was server crashed some time ok then some time map not changed server crashed :(

**Comment by SmileYzn** [comment]
Server is now pausing correctly, also votemap crashes has been fixed...
