### ISSUE TITLE
Captain choosing

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#92]
When captain leaving during vote, you can choose another captain. 
And both captain choose for same side.

https://www.youtube.com/watch?v=2CJ3SxcUwik

Another bug happened yesterday is when captain leave during choosing. 
Last player cant join since new captain dont have menu. Game stuck.

**Comment by SmileYzn** [comment]
BOT join randomly in team, I have sure that:

```C++
		g_engfuncs.pfnCVarSetString("mp_auto_join_team", "1");
		g_engfuncs.pfnCVarSetString("humans_join_team", "SPEC");
		g_engfuncs.pfnCVarSetString("bot_join_team", "SPEC");
		g_engfuncs.pfnCVarSetString("allow_spectators", "1");
```

Is working, did you choose Elliot that is in CT's team and is placed as captain?
Maybe need to update captain menu on player disconnect, and just avoid to choose an player that is not in spectator team.

**Comment by SmileYzn** [comment]
Tried to fix it on:

Linux
https://github.com/SmileYzn/MatchBot/actions/runs/5739163915

Windows
https://github.com/SmileYzn/MatchBot/actions/runs/5739163911

@yuyiken

**Comment by yuyiken** [comment]
> Is working, did you choose Elliot that is in CT's team and is placed as captain?

Yes this was the issue, menu wont get updated, when I kicked 2 bots, then 3º bot went to CT as captain and I choosed him on my team. 

About another bug It happened to me yesterday. Its like captain leave game when 1 guy left to choose. last guy cant connect to team and new captain hasnt menu.. what if no admins on server and game got stucked.

**Comment by SmileYzn** [comment]
> > Is working, did you choose Elliot that is in CT's team and is placed as captain?
> 
> Yes this was the issue, menu wont get updated, when I kicked 2 bots, then 3º bot went to CT as captain and I choosed him on my team.
> 
> About another bug It happened to me yesterday. Its like captain leave game when 1 guy left to choose. last guy cant connect to team and new captain hasnt menu.. what if no admins on server and game got stucked.
> 
> > Tried to fix it on:
> > Linux https://github.com/SmileYzn/MatchBot/actions/runs/5739163915
> > Windows https://github.com/SmileYzn/MatchBot/actions/runs/5739163911
> > @yuyiken
> 
> Going to test ty so much.

Did you can make an video if happen?
I guess the last guy always need to be choosed automatically to avoid that
