### ISSUE TITLE
/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by that-is-not-great** [SmileYzn/MatchBot#95]
```
Operating System: Ubuntu 20.04.6 LTS
Kernel: Linux 5.4.0
Architecture: x86-64
```
      
your _pre compiled_ versions **work fine**
trying to _build from src_ **fails** with the latest [90ba092]

```
[ 1] <matchbot_mm.so>  badf load  matchbot_mm.so          v -        ini   -     -
```

```
[META] ERROR: dll: Failed query plugin '<matchbot_mm.so>'; Couldn't open file '/home/xxx/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so': ./libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/xxx/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so)
```

```
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

how to fix it? I can provide more info if needed

**Comment by SmileYzn** [comment]
Did you have any other metamod plugin running?

To be honest libstdc++.so.6 comes from HLDS folder, soo do not make sense to grep libstdc++.so.6 from system library.

Also here:

"
your pre compiled versions work fine
trying to build from src fails with the latest [https://github.com/SmileYzn/MatchBot/commit/90ba0922c4923d15499981f793640a3a7fc3a6a4]
"

What you want to say with this?

**Comment by SmileYzn** [comment]
As you can see, you need to build matchbot with gcc-4.8 using C++11, since it is compatible only with libstdc++ from HLDS / ReHLDS.

On HLDS latest glibcxx version available is GLIBCXX_3.4.16.

And out of this, i can only support builds generated by action builds i mean, official project builds!

**Comment by SmileYzn** [comment]
runs-on: ubuntu-latest
    container: ubuntu:18.04

Look at makefile.yml from github action.
