### ISSUE TITLE
[Issue] Ban question

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#98]
Hello, I wanted yo ask about ban.

When an admin tries to ban a player, there is a possibility that while the admin is selecting the player in the ban menu, the player can leave the game before being banned, which means that the player is not banned.

I got this logs as example:

```
L 08/27/2023 - 18:15:50: <admin1><STEAM_0:0:ADMINID> banned <target><STEAM_0:0:TARGETID> 0 min(s).
L 08/27/2023 - 18:15:50: Ban: "target<261><STEAM_0:0:TARGETID><>" was kicked and banned "permanently" by "Console"
```

This one prints when admin banned target player successfull.

`L 08/27/2023 - 20:34:23: <admin1><STEAM_0:0:ADMINID> banned <><> 0 min(s).`

This one prints when admin ban player who left game before ban. Since this userid not connected to server anymore. 

My question is possible to handle auth id instead of user id until they user close admin menu?

**Comment by SmileYzn** [comment]
How that log should be? did you have an example?
You welcome to do a pull request

**Comment by yuyiken** [comment]
No, I'm not asking about log, I just showing that if you try to ban someone when he desconects before ban, it wont ban him, My question is it possible to handle auth id instead of user id when menu is painted?

**Comment by yuyiken** [comment]
> Did you want in this menu ban an disconnected player? Use Player List menu to ban disconnected players, i think will be more ease.
> 
> Tip: You can use player list menu even if player still in game.
> 
> Maybe i need to get information from player list to normal ban too

Ok, it seems my bad, I have old version. I will test the newer one. If problem persists, I will reopen the issue.
